import React, { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, FileText, Play, ShieldAlert } from 'lucide-react'

interface Decision { decisionId:string; nodeId:string; label:string; urgency:string; risk:number; confidence:number; conflicts:number; priority:number; executiveImpact:number; recommendedAction:string; investigationBrief:string; remediationBrief:string; revalidationPlan:string[] }
interface Payload { decisions:Decision[]; summary:{total:number;critical:number;high:number;requiresInvestigation:number;executivePriority:number} }

export const SecurityDecisionPage: React.FC = () => {
 const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(''); const [selected,setSelected]=useState<Decision|null>(null); const [creating,setCreating]=useState(false)
 useEffect(()=>{ const token=localStorage.getItem('access_token')||''; fetch('/api/v1/assurance/decision-pack',{headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok) throw new Error('Decision pack unavailable'); return r.json()}).then(setData).catch(e=>setError(e.message)) },[])
 const stats=useMemo(()=>data?.summary,{data})
 const createAction=async()=>{ if(!selected || creating) return; setCreating(true); setError(''); try { const token=localStorage.getItem('access_token')||''; const response=await fetch('/api/v1/assurance/actions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({decision_id:selected.decisionId,owner:'Security Operations',sla_hours:selected.urgency==='critical'?8:selected.urgency==='high'?24:72})}); if(!response.ok) throw new Error('Unable to create remediation action'); const action=await response.json(); window.location.assign(`/assurance/actions/${action.actionId}`) } catch(e:any){ setError(e.message) } finally { setCreating(false) } }
 if(error && !data) return <div className="p-8 text-sm text-red-400">{error}</div>
 if(!data) return <div className="p-8 text-sm opacity-70">Building security decision pack…</div>
 return <div className="p-6 space-y-6">
  <header><div className="flex items-center gap-2 text-xs uppercase tracking-widest opacity-60"><ShieldAlert size={15}/> Decision Intelligence</div><h1 className="text-3xl font-semibold mt-2">Security Decision Command Center</h1><p className="opacity-65 mt-1">Risk, confidence, evidence, conflicts and executive impact distilled into actionable decisions.</p>{error && <p className="mt-2 text-xs text-red-400">{error}</p>}</header>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['Priority',stats?.executivePriority],['Critical',stats?.critical],['High',stats?.high],['Investigation',stats?.requiresInvestigation],['Decisions',stats?.total]].map(([k,v])=><div key={String(k)} className="rounded-xl border p-4"><div className="text-xs opacity-60">{k}</div><div className="text-2xl font-semibold mt-1">{v}</div></div>)}</div>
  <div className="grid lg:grid-cols-[1.4fr_.9fr] gap-5">
   <section className="rounded-2xl border overflow-hidden"><div className="p-4 border-b font-medium">Priority decision queue</div>{data.decisions.map((d,i)=><button key={d.decisionId} onClick={()=>setSelected(d)} className="w-full text-left p-4 border-b last:border-0 hover:bg-black/5 transition"><div className="flex items-center gap-3"><span className="text-xs opacity-50">#{i+1}</span><div className="flex-1"><div className="font-medium">{d.label}</div><div className="text-xs opacity-60 mt-1">{d.recommendedAction}</div></div><div className="text-right"><div className="font-semibold">{d.priority}</div><div className="text-[11px] opacity-50">priority</div></div><ArrowRight size={16} className="opacity-40"/></div><div className="flex gap-4 mt-3 text-[11px] opacity-60"><span>Risk {d.risk}</span><span>Confidence {d.confidence}%</span><span>Conflicts {d.conflicts}</span><span>Impact {d.executiveImpact}</span></div></button>)}</section>
   <aside className="rounded-2xl border p-5 space-y-5">{selected ? <><div><div className="text-xs uppercase tracking-wider opacity-50">Decision brief</div><h2 className="text-xl font-semibold mt-1">{selected.label}</h2></div><div className="grid grid-cols-3 gap-2"><div className="p-3 rounded-lg border"><div className="text-xs opacity-50">Risk</div><b>{selected.risk}</b></div><div className="p-3 rounded-lg border"><div className="text-xs opacity-50">Confidence</div><b>{selected.confidence}%</b></div><div className="p-3 rounded-lg border"><div className="text-xs opacity-50">Priority</div><b>{selected.priority}</b></div></div><div><div className="text-xs font-medium flex items-center gap-2"><AlertTriangle size={14}/> Investigation</div><p className="text-sm opacity-70 mt-2">{selected.investigationBrief}</p></div><div><div className="text-xs font-medium flex items-center gap-2"><ClipboardCheck size={14}/> Remediation</div><p className="text-sm opacity-70 mt-2">{selected.remediationBrief}</p></div><div><div className="text-xs font-medium">Re-validation plan</div><ul className="mt-2 space-y-2 text-sm opacity-70">{selected.revalidationPlan.map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={15}/>{x}</li>)}</ul></div><div className="grid grid-cols-3 gap-2"><button onClick={()=>location.href=`/validations/${selected.nodeId}/results`} className="px-3 py-2 rounded-lg border text-sm">Investigate</button><button onClick={()=>location.href='/reports'} className="px-3 py-2 rounded-lg border text-sm"><FileText size={14} className="inline mr-1"/>Report</button><button onClick={createAction} disabled={creating} className="px-3 py-2 rounded-lg bg-primary text-primary-foreground text-sm"><Play size={14} className="inline mr-1"/>{creating?'Creating…':'Start action'}</button></div></> : <div className="h-full flex items-center justify-center text-sm opacity-50">Select a decision to inspect its brief.</div>}</aside>
  </div>
 </div>
}
