import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, FileText, Plus, RefreshCw, ShieldCheck, X } from 'lucide-react'
import { apiHelpers } from '@/services/api'
import { useLanguageStore } from '@/stores/languageStore'
import { toast } from 'sonner'

type Report={id:string;project_id:string;scan_id?:string|null;title:string;report_type:string;format:string;status:string;file_size:number;generated_by:string;created_at:string;completed_at?:string|null}
type Project={id:string;name:string}

export const Reports=()=>{
 const t=useLanguageStore(s=>s.t); const qc=useQueryClient(); const [open,setOpen]=useState(false); const [projectId,setProjectId]=useState(''); const [scanId,setScanId]=useState(''); const [title,setTitle]=useState(''); const [type,setType]=useState('full'); const [format,setFormat]=useState('pdf'); const [creating,setCreating]=useState(false)
 const reports=useQuery<Report[]>({queryKey:['reports-center'],queryFn:()=>apiHelpers.get<Report[]>('/reports?limit=100')})
 const summary=useQuery<any>({queryKey:['reports-summary'],queryFn:()=>apiHelpers.get<any>('/dashboard/summary')})
 const risk=useQuery<any>({queryKey:['reports-risk'],queryFn:()=>apiHelpers.get<any>('/dashboard/risk-distribution')})
 const projects=useQuery<Project[]>({queryKey:['reports-projects'],queryFn:()=>apiHelpers.get<any>('/projects/')})
 const create=async()=>{if(!projectId||!title.trim())return;setCreating(true);try{await apiHelpers.post('/reports/',{project_id:projectId,scan_id:scanId||null,title:title.trim(),description:'',report_type:type,format,template_id:type});await qc.invalidateQueries({queryKey:['reports-center']});setOpen(false);setTitle('');setScanId('');toast.success(t('Report created successfully'))}catch(e:any){toast.error(e?.response?.data?.detail||e?.message||t('Unable to create report'))}finally{setCreating(false)}}
 const download=(id:string)=>{window.open(`/api/v1/reports/${id}/download`,'_blank','noopener,noreferrer')}
 return <div className="space-y-6 pb-10">
  <section className="enterprise-card rounded-3xl p-6 md:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-primary"><FileText className="h-4 w-4"/>{t('Reports')}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{t('Report center')}</h1><p className="mt-2 text-sm text-muted-foreground">{t('Persisted DataExport reports generated from project, scan, finding and evidence records.')}</p></div><div className="flex gap-2"><button type="button" onClick={()=>{void reports.refetch()}} className="rounded-xl border p-2.5"><RefreshCw className={reports.isFetching?'h-4 w-4 animate-spin':'h-4 w-4'}/></button><button type="button" onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4"/>{t('Generate report')}</button></div></div></section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[t('Security score'),summary.data?.security_score],[t('Critical'),risk.data?.critical],[t('Vulnerabilities'),summary.data?.total_vulnerabilities],[t('Evidence'),summary.data?.total_evidence]].map(([label,value])=><div key={String(label)} className="enterprise-card rounded-2xl p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-semibold">{value==null?'—':String(value)}</div></div>)}</section>
  <section className="enterprise-card overflow-hidden rounded-2xl"><div className="border-b px-5 py-4"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-primary"/>{t('Generated reports')}</div></div>{reports.isLoading?<div className="p-12 text-center text-sm text-muted-foreground">{t('Loading...')}</div>:reports.isError?<div className="p-12 text-center"><p className="text-sm text-muted-foreground">{t('Unable to load persisted reports')}</p><button type="button" onClick={()=>reports.refetch()} className="mt-4 rounded-xl border px-4 py-2 text-sm">{t('Retry')}</button></div>:reports.data?.length?<div className="divide-y divide-border/70">{reports.data.map(item=><div key={item.id} className="flex flex-wrap items-center gap-4 px-5 py-4 hover:bg-muted/20"><div className="min-w-0 flex-1"><div className="font-semibold">{item.title}</div><div className="mt-1 text-xs text-muted-foreground">{item.report_type} · {item.format} · {item.status} · {new Date(item.created_at).toLocaleString()}</div><div className="mt-1 font-mono text-[10px] text-muted-foreground">{item.id}</div></div><button type="button" onClick={()=>download(item.id)} disabled={item.status!=='completed'} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold disabled:opacity-40"><Download className="h-3.5 w-3.5"/>{t('Download')}</button></div>)}</div>:<div className="p-14 text-center text-sm text-muted-foreground">{t('No reports available')}</div>}</section>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4 backdrop-blur-sm"><div className="enterprise-card w-full max-w-lg rounded-3xl p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">{t('Generate report')}</h2><p className="mt-1 text-xs text-muted-foreground">{t('The server builds the report only from persisted records.')}</p></div><button onClick={()=>setOpen(false)} className="rounded-xl border p-2"><X className="h-4 w-4"/></button></div><div className="mt-6 space-y-4"><label className="block"><span className="text-sm font-medium">{t('Project')}</span><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="">{t('Select project')}</option>{(projects.data||[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block"><span className="text-sm font-medium">{t('Title')}</span><input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="text-sm font-medium">{t('Report type')}</span><select value={type} onChange={e=>setType(e.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="full">full</option><option value="findings">findings</option><option value="evidence">evidence</option><option value="scan">scan</option></select></label><label><span className="text-sm font-medium">{t('Format')}</span><select value={format} onChange={e=>setFormat(e.target.value)} className="mt-2 h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="pdf">PDF</option><option value="json">JSON</option><option value="csv">CSV</option></select></label></div></div><div className="mt-7 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5 text-sm">{t('Cancel')}</button><button onClick={create} disabled={creating||!projectId||!title.trim()} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">{creating?t('Generating…'):t('Generate report')}</button></div></div></div>}
 </div>
}
