# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('scan_started', 'Scan Started'), ('scan_completed', 'Scan Completed'), ('scan_failed', 'Scan Failed'), ('scan_cancelled', 'Scan Cancelled'), ('vuln_critical_found', 'Critical Vulnerability Found'), ('vuln_high_found', 'High Vulnerability Found'), ('vuln_assigned', 'Vulnerability Assigned'), ('vuln_status_changed', 'Vulnerability Status Changed'), ('vuln_fixed', 'Vulnerability Fixed'), ('report_generated', 'Report Generated'), ('report_failed', 'Report Generation Failed'), ('compliance_violation', 'Compliance Violation'), ('compliance_report', 'Compliance Report Ready'), ('system_backup_completed', 'Backup Completed'), ('system_backup_failed', 'Backup Failed'), ('system_maintenance', 'Maintenance Window'), ('system_service_down', 'Service Down'), ('user_invited', 'User Invited'), ('user_mentioned', 'User Mentioned')], max_length=50, unique=True, verbose_name='event type')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_channels', models.JSONField(default=list, verbose_name='default channels')),
                ('email_subject', models.CharField(blank=True, max_length=200, verbose_name='email subject')),
                ('email_template', models.TextField(blank=True, verbose_name='email template')),
                ('slack_template', models.TextField(blank=True, verbose_name='slack template')),
                ('teams_template', models.TextField(blank=True, verbose_name='teams template')),
                ('in_app_title', models.CharField(blank=True, max_length=200, verbose_name='in-app title')),
                ('in_app_message', models.TextField(blank=True, verbose_name='in-app message')),
                ('available_variables', models.JSONField(default=list, verbose_name='available variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('in_app', 'In-App'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20, verbose_name='type')),
                ('config', models.JSONField(default=dict, verbose_name='configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='projects.project')),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(verbose_name='period start')),
                ('period_end', models.DateTimeField(verbose_name='period end')),
                ('notification_count', models.PositiveIntegerField(default=0, verbose_name='notification count')),
                ('critical_count', models.PositiveIntegerField(default=0, verbose_name='critical count')),
                ('high_count', models.PositiveIntegerField(default=0, verbose_name='high count')),
                ('medium_count', models.PositiveIntegerField(default=0, verbose_name='medium count')),
                ('low_count', models.PositiveIntegerField(default=0, verbose_name='low count')),
                ('content', models.JSONField(default=dict, verbose_name='content')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Digest',
                'verbose_name_plural': 'Notification Digests',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email enabled')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='in-app enabled')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='push enabled')),
                ('digest_enabled', models.BooleanField(default=False, verbose_name='digest enabled')),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='digest frequency')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='quiet hours end')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('event_preferences', models.JSONField(default=dict, verbose_name='event preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='projects.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50, verbose_name='event type')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=15, verbose_name='status')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='resource type')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='resource ID')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='action URL')),
                ('channels', models.JSONField(default=list, verbose_name='channels')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='retry count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='max retries')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['project', 'event_type'], name='notificatio_project_92f85a_idx')],
            },
        ),
    ]
