# Generated by Django 5.2.17 on 2026-08-31

import hashlib
import re
from urllib.parse import urlsplit, urlunsplit

from django.db import migrations, models
import django.db.models.deletion
import uuid


def _clean(value):
    return re.sub(r"\s+", " ", str(value or "").strip().lower())


def _normalize_target(value):
    raw = str(value or "").strip()
    if not raw:
        return ""
    try:
        parsed = urlsplit(raw if "://" in raw else f"//{raw}")
        scheme = parsed.scheme.lower()
        hostname = (parsed.hostname or "").lower().rstrip(".")
        port = parsed.port
        default_port = (scheme == "https" and port == 443) or (scheme == "http" and port == 80)
        netloc = hostname if not port or default_port else f"{hostname}:{port}"
        path = parsed.path or "/"
        return urlunsplit((scheme, netloc, path.rstrip("/") or "/", "", ""))
    except ValueError:
        return _clean(raw).rstrip("/")


def _rule_key(vulnerability):
    title = _clean(vulnerability.title)
    aliases = {
        "https response lacks strict-transport-security": "missing-hsts",
        "missing strict-transport-security": "missing-hsts",
        "missing hsts": "missing-hsts",
    }
    if title in aliases:
        return aliases[title]
    parts = (_clean(vulnerability.category), _clean(vulnerability.cwe_id), title)
    return "|".join(part for part in parts if part)[:200]


def _fingerprint(vulnerability):
    raw = vulnerability.raw_data or {}
    target = vulnerability.url or raw.get("url") or raw.get("target") or raw.get("asset") or ""
    normalized_target = _normalize_target(target)
    rule = _rule_key(vulnerability)
    asset_key = str(vulnerability.asset_id or _clean(raw.get("asset")))
    parts = [
        "v1",
        str(vulnerability.project_id),
        asset_key,
        normalized_target,
        _clean(vulnerability.method),
        _clean(vulnerability.parameter),
        _clean(vulnerability.file_path),
        _clean(vulnerability.function_name),
        rule,
    ]
    return hashlib.sha256("\x1f".join(parts).encode("utf-8")).hexdigest(), rule, normalized_target


def backfill_canonical_findings(apps, schema_editor):
    Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")
    CanonicalFinding = apps.get_model("vulnerabilities", "CanonicalFinding")

    for vulnerability in Vulnerability.objects.all().iterator():
        fingerprint, rule_key, normalized_target = _fingerprint(vulnerability)
        canonical, created = CanonicalFinding.objects.get_or_create(
            project_id=vulnerability.project_id,
            fingerprint=fingerprint,
            defaults={
                "rule_key": rule_key,
                "title": vulnerability.title,
                "category": vulnerability.category or "",
                "normalized_target": normalized_target,
                "source_engines": [vulnerability.source_engine] if vulnerability.source_engine else [],
                "observation_count": 0,
            },
        )

        if vulnerability.source_engine:
            source_engines = list(canonical.source_engines or [])
            if vulnerability.source_engine not in source_engines:
                source_engines.append(vulnerability.source_engine)
                canonical.source_engines = source_engines
                canonical.save(update_fields=["source_engines", "updated_at", "last_seen"])

        if not vulnerability.canonical_finding_id:
            vulnerability.canonical_finding_id = canonical.pk
            vulnerability.save(update_fields=["canonical_finding"])

        CanonicalFinding.objects.filter(pk=canonical.pk).update(
            observation_count=Vulnerability.objects.filter(canonical_finding_id=canonical.pk).count(),
        )


def reverse_backfill(apps, schema_editor):
    Vulnerability = apps.get_model("vulnerabilities", "Vulnerability")
    Vulnerability.objects.update(canonical_finding=None)


class Migration(migrations.Migration):
    dependencies = [
        ("vulnerabilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalFinding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fingerprint", models.CharField(max_length=64, verbose_name="canonical fingerprint")),
                ("rule_key", models.CharField(max_length=200, verbose_name="rule key")),
                ("title", models.CharField(max_length=300, verbose_name="canonical title")),
                ("category", models.CharField(blank=True, max_length=50, verbose_name="category")),
                ("normalized_target", models.CharField(blank=True, max_length=1000, verbose_name="normalized target")),
                ("source_engines", models.JSONField(blank=True, default=list, verbose_name="source engines")),
                ("observation_count", models.PositiveIntegerField(default=0, verbose_name="observation count")),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="canonical_findings", to="projects.project")),
            ],
            options={
                "verbose_name": "Canonical Finding",
                "verbose_name_plural": "Canonical Findings",
            },
        ),
        migrations.AddConstraint(
            model_name="canonicalfinding",
            constraint=models.UniqueConstraint(fields=("project", "fingerprint"), name="uniq_canonical_finding_project_fingerprint"),
        ),
        migrations.AddIndex(
            model_name="canonicalfinding",
            index=models.Index(fields=["project", "rule_key"], name="vulnerabili_project_canon_rule_idx"),
        ),
        migrations.AddIndex(
            model_name="canonicalfinding",
            index=models.Index(fields=["project", "category"], name="vulnerabili_project_canon_cat_idx"),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="canonical_finding",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="observations", to="vulnerabilities.canonicalfinding"),
        ),
        migrations.AddIndex(
            model_name="vulnerability",
            index=models.Index(fields=["canonical_finding"], name="vulnerabili_canon_id_idx"),
        ),
        migrations.RunPython(backfill_canonical_findings, reverse_backfill),
    ]
