# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='version')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('confidence', models.FloatField(default=0.0, verbose_name='confidence')),
                ('source', models.CharField(max_length=50, verbose_name='source')),
                ('evidence', models.TextField(blank=True, verbose_name='evidence')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Technology Fingerprint',
                'verbose_name_plural': 'Technology Fingerprints',
                'ordering': ['-confidence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=220, verbose_name='slug')),
                ('type', models.CharField(choices=[('source_code', 'Source Code'), ('website', 'Website (URL)'), ('ip_address', 'IP Address'), ('domain', 'Domain'), ('api_endpoint', 'API Endpoint'), ('file', 'File Upload'), ('docker_image', 'Docker Image'), ('network_range', 'Network Range'), ('repository', 'Code Repository'), ('cloud_resource', 'Cloud Resource'), ('kubernetes', 'Kubernetes Cluster'), ('mobile_app', 'Mobile Application')], max_length=30, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20, verbose_name='environment')),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='criticality')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='configuration')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='last scanned at')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='scan count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('depends_on', 'Depends On'), ('contains', 'Contains'), ('connects_to', 'Connects To'), ('hosts', 'Hosts'), ('deployed_on', 'Deployed On'), ('same_as', 'Same As')], max_length=20, verbose_name='type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_relationships', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='assets.asset')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Relationship',
                'verbose_name_plural': 'Asset Relationships',
            },
        ),
        migrations.CreateModel(
            name='AssetScanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('high_count', models.PositiveIntegerField(default=0)),
                ('medium_count', models.PositiveIntegerField(default=0)),
                ('low_count', models.PositiveIntegerField(default=0)),
                ('scan_duration', models.FloatField(default=0, verbose_name='scan duration (seconds)')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Scan History',
                'verbose_name_plural': 'Asset Scan History',
                'ordering': ['-created_at'],
            },
        ),
    ]
