# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='assetrelationship',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_relationships', to='projects.project'),
        ),
        migrations.AddField(
            model_name='assetrelationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrelationship',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetscanhistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetscanhistory',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_history', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='technologyfingerprint',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='assets.asset'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'type'], name='assets_asse_project_b73b44_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'environment'], name='assets_asse_project_248405_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['project', 'is_active'], name='assets_asse_project_016c8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('project', 'slug')},
        ),
        migrations.AddIndex(
            model_name='assetrelationship',
            index=models.Index(fields=['project', 'source'], name='assets_asse_project_210b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrelationship',
            index=models.Index(fields=['project', 'target'], name='assets_asse_project_bd39d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetrelationship',
            unique_together={('source', 'target', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='technologyfingerprint',
            index=models.Index(fields=['asset', 'category'], name='assets_tech_asset_i_da10f7_idx'),
        ),
    ]
