# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_preserve_authorization_lineage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrelationship',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
