import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ShieldCheck, FolderKanban, Server, Activity, AlertTriangle, TrendingUp, Plus, FileText, Settings, Bug, ArrowUpRight, RefreshCw, ArrowRight, CheckCircle2, type LucideIcon } from 'lucide-react'
import ReactECharts from 'echarts-for-react'
import { cn } from '@/utils/cn'
import { apiHelpers } from '@/services/api'
import { Skeleton, CardSkeleton } from '@/components/ui/skeleton'
import { IntelligencePanel } from '@/components/dashboard/IntelligencePanel'

interface DashboardSummary { security_score?: number; total_projects?: number; total_assets?: number; total_validations?: number; critical?: number; high?: number }
interface RiskDistribution { critical?: number; high?: number; medium?: number; low?: number; informational?: number }
interface TrendPoint { date: string; score: number }
interface RecentValidation { id?: string; validation_id?: string; target_value?: string; target?: string; project_name?: string; status?: string }

const StatCard = ({ icon: Icon, label, value, hint, tone = 'default' }: { icon: LucideIcon; label: string; value: number | string | undefined; hint: string; tone?: 'default' | 'danger' | 'warning' }) => (
  <div className="aegis-surface aegis-surface-hover p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="aegis-kicker flex items-center gap-1.5"><Icon className="h-3.5 w-3.5" />{label}</div><div className={cn('mt-2 text-2xl font-bold tracking-tight', tone === 'danger' && 'text-destructive', tone === 'warning' && 'text-amber-500')}>{value ?? '—'}</div></div><div className="rounded-xl border bg-muted/50 p-2 text-muted-foreground"><Icon className="h-4 w-4" /></div></div><div className="mt-2 text-[11px] text-muted-foreground">{hint}</div></div>
)
const ChartEmpty = ({ label }: { label: string }) => <div className="flex h-56 items-center justify-center rounded-xl border border-dashed bg-muted/20 text-sm text-muted-foreground">{label}</div>
const ScoreRing = ({ score }: { score?: number }) => { const value = score ?? 0; const radius = 42; const circumference = 2 * Math.PI * radius; const offset = circumference - (Math.max(0, Math.min(100, value)) / 100) * circumference; return <div className="relative h-28 w-28 shrink-0"><svg viewBox="0 0 100 100" className="h-full w-full -rotate-90" aria-label={`Security score ${value} out of 100`}><circle cx="50" cy="50" r={radius} fill="none" stroke="currentColor" strokeWidth="8" className="text-muted/50" /><circle cx="50" cy="50" r={radius} fill="none" stroke="currentColor" strokeWidth="8" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={offset} className="text-primary transition-all duration-700" /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-2xl font-bold tracking-tight">{score ?? '—'}</span><span className="text-[10px] uppercase tracking-wider text-muted-foreground">/ 100</span></div></div> }

export const Dashboard = () => {
  const summaryQuery = useQuery({ queryKey: ['dash-summary'], queryFn: () => apiHelpers.get<DashboardSummary>('/dashboard/summary') })
  const riskQuery = useQuery({ queryKey: ['dash-risk'], queryFn: () => apiHelpers.get<RiskDistribution>('/dashboard/risk-distribution') })
  const trendsQuery = useQuery({ queryKey: ['dash-trends'], queryFn: () => apiHelpers.get<TrendPoint[]>('/dashboard/trends?days=30') })
  const recentQuery = useQuery({ queryKey: ['dash-recent'], queryFn: () => apiHelpers.get<RecentValidation[]>('/dashboard/recent-validations?limit=5') })
  if (summaryQuery.isLoading) return <div className="space-y-6" aria-busy="true"><div className="h-32 rounded-2xl bg-muted animate-pulse" /><div className="grid grid-cols-1 gap-3 md:grid-cols-3 xl:grid-cols-6">{Array.from({ length: 6 }).map((_, i) => <CardSkeleton key={i} />)}</div><div className="grid gap-4 xl:grid-cols-3"><Skeleton className="h-72 xl:col-span-2" /><Skeleton className="h-72" /></div></div>
  if (summaryQuery.isError) return <div className="aegis-surface flex min-h-72 flex-col items-center justify-center p-8 text-center"><div className="mb-4 rounded-full border border-destructive/20 bg-destructive/10 p-3"><AlertTriangle className="h-7 w-7 text-destructive" /></div><h2 className="text-lg font-semibold">Security overview unavailable</h2><p className="mt-1 max-w-md text-sm text-muted-foreground">The platform API could not provide the current posture. Your session may still be valid; retry the dashboard request.</p><button onClick={() => summaryQuery.refetch()} className="aegis-button aegis-button-primary mt-5"><RefreshCw className="h-4 w-4" />Retry</button></div>
  const summary = summaryQuery.data ?? {}; const risk = riskQuery.data; const trends = Array.isArray(trendsQuery.data) ? trendsQuery.data : []; const recent = Array.isArray(recentQuery.data) ? recentQuery.data : []; const score = typeof summary.security_score === 'number' ? Math.round(summary.security_score) : undefined; const riskValues = risk ? [risk.critical, risk.high, risk.medium, risk.low, risk.informational].map((v) => Number(v || 0)) : []; const postureLabel = score === undefined ? 'Awaiting posture data' : score >= 90 ? 'Strong security posture' : score >= 75 ? 'Healthy posture' : score >= 60 ? 'Attention recommended' : 'Immediate attention required'
  const trendOption = trends.length ? { tooltip: { trigger: 'axis' }, grid: { left: 12, right: 12, top: 20, bottom: 20, containLabel: true }, xAxis: { type: 'category', data: trends.map((item) => String(item.date).slice(5)), boundaryGap: false, axisLine: { show: false }, axisTick: { show: false } }, yAxis: { type: 'value', min: 0, max: 100, splitLine: { lineStyle: { type: 'dashed' } } }, series: [{ type: 'line', data: trends.map((item) => item.score), smooth: true, symbol: 'circle', symbolSize: 5, areaStyle: { opacity: 0.08 }, lineStyle: { width: 2 } }] } : null
  const severityOption = risk ? { tooltip: { trigger: 'axis' }, grid: { left: 12, right: 12, top: 12, bottom: 20, containLabel: true }, xAxis: { type: 'category', data: ['Critical', 'High', 'Medium', 'Low', 'Info'], axisLine: { show: false }, axisTick: { show: false } }, yAxis: { type: 'value', minInterval: 1, splitLine: { lineStyle: { type: 'dashed' } } }, series: [{ type: 'bar', data: riskValues, barMaxWidth: 34, itemStyle: { borderRadius: [6, 6, 0, 0] } }] } : null
  return <div className="space-y-6">
    <section className="aegis-surface relative overflow-hidden p-5 lg:p-6"><div className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-center"><div className="min-w-0"><div className="aegis-kicker mb-2 flex items-center gap-2 text-primary"><span className="h-1.5 w-1.5 rounded-full bg-primary" />Security Operations</div><h1 className="text-2xl font-bold tracking-tight lg:text-3xl">Security command overview</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A decision-ready view of validation coverage, exposure and security posture across your workspace.</p><div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="h-3.5 w-3.5 text-primary" />Platform connected</span><span>•</span><span>Live API data</span></div></div><div className="flex items-center gap-5 rounded-2xl border bg-background/60 p-4 backdrop-blur-sm"><ScoreRing score={score} /><div><div className="text-sm font-semibold">{postureLabel}</div><p className="mt-1 max-w-[190px] text-xs leading-5 text-muted-foreground">{score !== undefined ? 'Based on the latest platform security assessment.' : 'Run a validation to establish your first posture baseline.'}</p></div></div></div><div className="relative mt-5 flex flex-wrap gap-2"><Link to="/validations/new" className="aegis-button aegis-button-primary"><Plus className="h-4 w-4" />New validation</Link><Link to="/projects" className="aegis-button aegis-button-secondary">Projects <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></section>
    <section className="grid grid-cols-1 gap-3 md:grid-cols-3 xl:grid-cols-6"><StatCard icon={ShieldCheck} label="Security score" value={score !== undefined ? `${score}/100` : undefined} hint={postureLabel} /><StatCard icon={FolderKanban} label="Projects" value={summary.total_projects} hint="Active workspace scope" /><StatCard icon={Server} label="Assets" value={summary.total_assets} hint="Across your projects" /><StatCard icon={Activity} label="Validations" value={summary.total_validations} hint="Recorded executions" /><StatCard icon={AlertTriangle} label="Critical" value={risk?.critical ?? summary.critical} hint="Requires immediate review" tone="danger" /><StatCard icon={Bug} label="High" value={risk?.high ?? summary.high} hint="Priority remediation" tone="warning" /></section>
    <IntelligencePanel />
    <section className="grid gap-4 xl:grid-cols-3"><div className="aegis-surface p-5 xl:col-span-2"><div className="mb-3 flex items-start justify-between"><div><h2 className="aegis-title flex items-center gap-2"><TrendingUp className="h-4 w-4 text-primary" />Security score trend</h2><p className="aegis-subtitle mt-1">Last 30 days</p></div><span className="rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Posture</span></div>{trendsQuery.isLoading ? <Skeleton className="h-56 w-full" /> : trendsQuery.isError ? <ChartEmpty label="Unable to load trend data" /> : trendOption ? <ReactECharts option={trendOption} style={{ height: 224 }} /> : <ChartEmpty label="No trend data yet" />}</div><div className="aegis-surface p-5"><div className="mb-3"><h2 className="aegis-title">Risk distribution</h2><p className="aegis-subtitle mt-1">Findings by severity</p></div>{riskQuery.isLoading ? <Skeleton className="h-56 w-full" /> : riskQuery.isError ? <ChartEmpty label="Unable to load risk data" /> : risk ? <ReactECharts option={{ tooltip: { trigger: 'item' }, legend: { bottom: 0, icon: 'circle', itemWidth: 7, itemHeight: 7 }, series: [{ type: 'pie', radius: ['46%', '70%'], center: ['50%', '45%'], data: [{ value: risk.critical, name: 'Critical' }, { value: risk.high, name: 'High' }, { value: risk.medium, name: 'Medium' }, { value: risk.low, name: 'Low' }, { value: risk.informational, name: 'Info' }], label: { show: false } }] }} style={{ height: 224 }} /> : <ChartEmpty label="No risk data yet" />}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="aegis-surface p-5"><div className="mb-3"><h2 className="aegis-title">Findings by severity</h2><p className="aegis-subtitle mt-1">Current open risk distribution</p></div>{severityOption ? <ReactECharts option={severityOption} style={{ height: 208 }} /> : <ChartEmpty label="No findings data yet" />}</div><div className="aegis-surface p-5"><div className="mb-3 flex items-center justify-between"><div><h2 className="aegis-title">Recent validations</h2><p className="aegis-subtitle mt-1">Latest execution activity</p></div><Link to="/scan" className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline">View all <ArrowRight className="h-3 w-3" /></Link></div><div className="space-y-2">{recent.length ? recent.slice(0, 5).map((item) => <Link key={item.id || item.validation_id} to={item.id ? `/validations/${item.id}/results` : '/scan'} className="flex items-center justify-between rounded-xl border px-3 py-2.5 transition-colors hover:bg-accent"><div className="min-w-0"><div className="truncate font-mono text-xs font-semibold">{item.id || item.validation_id || 'Validation'}</div><div className="mt-0.5 truncate text-xs text-muted-foreground">{item.target_value || item.target || item.project_name || '—'}</div></div><span className="ml-3 shrink-0 rounded-full bg-muted px-2 py-1 text-[10px] font-semibold uppercase">{item.status || 'unknown'}</span></Link>) : <div className="rounded-xl border border-dashed py-10 text-center text-sm text-muted-foreground">No validation activity yet.</div>}</div></div></section>
    <section className="aegis-surface p-5"><div className="mb-3"><h2 className="aegis-title">Quick actions</h2><p className="aegis-subtitle mt-1">Start the next security workflow</p></div><div className="grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-6">{[[Plus,'New validation','/validations/new'],[FolderKanban,'Projects','/projects'],[Server,'Assets','/assets'],[Bug,'Findings','/vulnerabilities'],[FileText,'Reports','/reports'],[Settings,'Settings','/settings']].map(([Icon,label,href]) => <Link key={String(label)} to={String(href)} className="group rounded-xl border p-3 transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:bg-accent"><Icon className="h-5 w-5 text-muted-foreground transition-colors group-hover:text-primary" /><div className="mt-2 text-xs font-semibold">{String(label)}</div></Link>)}</div></section>
  </div>
}
