# Generated by Django 5.2.17 on 2026-08-29 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partial', 'Partially Compliant'), ('not_applicable', 'Not Applicable'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=20, verbose_name='status')),
                ('evidence', models.TextField(blank=True, verbose_name='evidence')),
                ('remediation_plan', models.TextField(blank=True, verbose_name='remediation plan')),
                ('remediation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='remediation deadline')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='assessed at')),
                ('next_review', models.DateTimeField(blank=True, null=True, verbose_name='next review')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Assessment',
                'verbose_name_plural': 'Compliance Assessments',
                'ordering': ['framework', 'control__control_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_id', models.CharField(max_length=50, verbose_name='control ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('priority', models.CharField(choices=[('mandatory', 'Mandatory'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], default='high', max_length=20, verbose_name='priority')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('related_controls', models.JSONField(blank=True, default=list, verbose_name='related controls')),
                ('references', models.JSONField(blank=True, default=list, verbose_name='references')),
                ('implementation_guidance', models.TextField(blank=True, verbose_name='implementation guidance')),
                ('testing_procedure', models.TextField(blank=True, verbose_name='testing procedure')),
                ('remediation_deadline_days', models.PositiveIntegerField(default=30, verbose_name='remediation deadline (days)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Control',
                'verbose_name_plural': 'Compliance Controls',
                'ordering': ['framework', 'control_id'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('framework_type', models.CharField(choices=[('nist_800_53', 'NIST 800-53'), ('nist_csf', 'NIST Cybersecurity Framework'), ('iso_27001', 'ISO 27001'), ('iso_27002', 'ISO 27002'), ('pci_dss', 'PCI DSS'), ('hipaa', 'HIPAA'), ('gdpr', 'GDPR'), ('soc2', 'SOC 2'), ('cis_controls', 'CIS Controls'), ('cis_benchmarks', 'CIS Benchmarks'), ('mitre_attack', 'MITRE ATT&CK'), ('custom', 'Custom Framework')], max_length=30, verbose_name='type')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='version')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_system', models.BooleanField(default=False, verbose_name='system')),
                ('controls_count', models.PositiveIntegerField(default=0, verbose_name='controls count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Framework',
                'verbose_name_plural': 'Compliance Frameworks',
                'ordering': ['framework_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('overall_status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partial', 'Partially Compliant'), ('not_applicable', 'Not Applicable'), ('not_assessed', 'Not Assessed')], max_length=20, verbose_name='overall status')),
                ('total_controls', models.PositiveIntegerField(default=0, verbose_name='total controls')),
                ('compliant_count', models.PositiveIntegerField(default=0, verbose_name='compliant')),
                ('non_compliant_count', models.PositiveIntegerField(default=0, verbose_name='non-compliant')),
                ('partial_count', models.PositiveIntegerField(default=0, verbose_name='partial')),
                ('not_applicable_count', models.PositiveIntegerField(default=0, verbose_name='not applicable')),
                ('compliance_percentage', models.FloatField(default=0, verbose_name='compliance %')),
                ('report_data', models.JSONField(default=dict, verbose_name='report data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('policy_type', models.CharField(choices=[('security', 'Security Policy'), ('data_protection', 'Data Protection'), ('access_control', 'Access Control'), ('incident_response', 'Incident Response'), ('vulnerability_management', 'Vulnerability Management'), ('custom', 'Custom Policy')], max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=15, verbose_name='status')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('description', models.TextField(verbose_name='description')),
                ('content', models.TextField(verbose_name='content')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('effective_date', models.DateTimeField(blank=True, null=True, verbose_name='effective date')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='review date')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
