# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceassessment',
            name='assessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='findings',
            field=models.ManyToManyField(blank=True, related_name='compliance_assessments', to='vulnerabilities.vulnerability'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assessments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_assessments', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compliance.compliancecontrol'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceframework',
            unique_together={('framework_type', 'version')},
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='complianceassessment',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='compliance.complianceframework'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_compliance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='projects.project'),
        ),
        migrations.AddField(
            model_name='policy',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approved_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='compliancecontrol',
            index=models.Index(fields=['framework', 'priority'], name='compliance__framewo_8a9834_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecontrol',
            unique_together={('framework', 'control_id')},
        ),
        migrations.AddIndex(
            model_name='complianceassessment',
            index=models.Index(fields=['project', 'status'], name='compliance__project_ae20e7_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceassessment',
            index=models.Index(fields=['framework', 'status'], name='compliance__framewo_a9d67e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceassessment',
            unique_together={('project', 'framework', 'control')},
        ),
    ]
