# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mitre_id', models.CharField(max_length=20, unique=True, verbose_name='MITRE ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('tactic', models.CharField(choices=[('reconnaissance', 'Reconnaissance'), ('resource_development', 'Resource Development'), ('initial_access', 'Initial Access'), ('execution', 'Execution'), ('persistence', 'Persistence'), ('privilege_escalation', 'Privilege Escalation'), ('defense_evasion', 'Defense Evasion'), ('credential_access', 'Credential Access'), ('discovery', 'Discovery'), ('lateral_movement', 'Lateral Movement'), ('collection', 'Collection'), ('command_and_control', 'Command and Control'), ('exfiltration', 'Exfiltration'), ('impact', 'Impact')], max_length=30, verbose_name='tactic')),
                ('description', models.TextField(verbose_name='description')),
                ('platforms', models.JSONField(default=list, verbose_name='platforms')),
                ('permissions_required', models.JSONField(default=list, verbose_name='permissions required')),
                ('data_sources', models.JSONField(default=list, verbose_name='data sources')),
                ('detection_rules', models.JSONField(default=list, verbose_name='detection rules')),
                ('mitigation_strategies', models.JSONField(default=list, verbose_name='mitigation strategies')),
                ('related_techniques', models.JSONField(default=list, verbose_name='related techniques')),
                ('examples', models.JSONField(default=list, verbose_name='examples')),
                ('references', models.JSONField(default=list, verbose_name='references')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attack Pattern',
                'verbose_name_plural': 'Attack Patterns',
                'ordering': ['mitre_id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('best_practice', 'Best Practice'), ('remediation_guide', 'Remediation Guide'), ('security_policy', 'Security Policy'), ('lesson_learned', 'Lesson Learned'), ('attack_pattern', 'Attack Pattern'), ('defense_gap', 'Defense Gap'), ('tool_guide', 'Tool Guide'), ('faq', 'FAQ'), ('template', 'Template')], max_length=30, verbose_name='type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('under_review', 'Under Review')], default='draft', max_length=20, verbose_name='status')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='difficulty')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('content', models.TextField(verbose_name='content')),
                ('content_html', models.TextField(blank=True, verbose_name='content HTML')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='helpful count')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, verbose_name='not helpful count')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='version')),
                ('change_log', models.TextField(blank=True, verbose_name='change log')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='knowledge.knowledgearticle')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='related_to', to='knowledge.knowledgearticle')),
                ('related_controls', models.ManyToManyField(blank=True, related_name='knowledge_articles', to='compliance.compliancecontrol')),
                ('related_vulnerabilities', models.ManyToManyField(blank=True, related_name='knowledge_articles', to='vulnerabilities.vulnerability')),
                ('reviewers', models.ManyToManyField(blank=True, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticleView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='duration (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='knowledge.knowledgearticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article View',
                'verbose_name_plural': 'Article Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.knowledgecategory'),
        ),
        migrations.CreateModel(
            name='RemediationPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('vulnerability_types', models.JSONField(default=list, verbose_name='vulnerability types')),
                ('severity_range', models.JSONField(default=list, verbose_name='severity range')),
                ('code_patterns', models.JSONField(default=list, verbose_name='code patterns')),
                ('fix_template', models.TextField(verbose_name='fix template')),
                ('fix_examples', models.JSONField(default=list, verbose_name='fix examples')),
                ('languages', models.JSONField(default=list, verbose_name='languages')),
                ('frameworks', models.JSONField(default=list, verbose_name='frameworks')),
                ('confidence', models.FloatField(default=0.8, verbose_name='confidence')),
                ('success_rate', models.FloatField(default=0, verbose_name='success rate')),
                ('times_applied', models.PositiveIntegerField(default=0, verbose_name='times applied')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patterns', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remediation Pattern',
                'verbose_name_plural': 'Remediation Patterns',
                'ordering': ['-confidence', '-success_rate'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticleFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 'Not Helpful'), (2, 'Neutral'), (3, 'Helpful'), (4, 'Very Helpful'), (5, 'Excellent')], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='knowledge.knowledgearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article Feedback',
                'verbose_name_plural': 'Article Feedbacks',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['status', 'category'], name='knowledge_k_status_c571cb_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tags'], name='knowledge_k_tags_751c39_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['author'], name='knowledge_k_author__2ea4bd_idx'),
        ),
    ]
