import React, { useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, CheckCircle2, ClipboardCheck, FileText, Play, ShieldAlert } from 'lucide-react'
import { Link } from 'react-router-dom'
import { DecisionIntelligencePanel } from '@/components/security/DecisionIntelligencePanel'

interface Decision { decisionId:string; nodeId:string; label:string; urgency:string; risk:number; confidence:number; conflicts:number; priority:number; executiveImpact:number; recommendedAction:string; investigationBrief:string; remediationBrief:string; revalidationPlan:string[] }
interface Payload { decisions:Decision[]; summary:{total:number;critical:number;high:number;requiresInvestigation:number;executivePriority:number} }

export const SecurityDecisionPage: React.FC = () => {
 const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(''); const [selected,setSelected]=useState<Decision|null>(null); const [creating,setCreating]=useState(false)
 const load=()=>{ const token=localStorage.getItem('access_token')||''; setError(''); return fetch('/api/v1/assurance/decision-pack',{headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok) throw new Error('Decision pack unavailable'); return r.json()}).then(setData).catch(e=>setError(e.message)) }
 useEffect(()=>{ void load() },[])
 const createAction=async()=>{ if(!selected || creating) return; setCreating(true); setError(''); try { const token=localStorage.getItem('access_token')||''; const response=await fetch('/api/v1/assurance/actions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({decision_id:selected.decisionId,owner:'Security Operations',sla_hours:selected.urgency==='critical'?8:selected.urgency==='high'?24:72})}); if(!response.ok) throw new Error('Unable to create remediation action'); const action=await response.json(); window.location.assign(`/assurance/actions/${action.actionId}`) } catch(e:any){ setError(e.message) } finally { setCreating(false) } }
 if(error && !data) return <div className="mx-auto grid min-h-[70vh] max-w-xl place-items-center p-6 text-center"><div><AlertTriangle className="mx-auto h-8 w-8 text-red-400"/><h1 className="mt-3 font-semibold text-white">Decision intelligence unavailable</h1><p className="mt-1 text-sm text-slate-400">The live decision pack could not be retrieved.</p><button type="button" onClick={()=>void load()} className="mt-4 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-200">Retry</button></div></div>
 if(!data) return <div className="grid min-h-[60vh] place-items-center text-sm text-slate-400">Building security decision pack…</div>
 const stats=data.summary
 return <div className="space-y-6">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-cyan-300"><ShieldAlert size={15}/> Decision Intelligence</div><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">Security Decision Command Center</h1><p className="mt-1 max-w-3xl text-sm text-slate-400">Turn risk, confidence, conflicts and executive impact into an auditable action path.</p></div><div className="flex gap-2"><Link to="/assurance/evidence" className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300">Evidence</Link><Link to="/assurance/conflicts" className="rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-slate-300">Conflicts</Link></div></header>
  <div className="grid grid-cols-2 gap-2 md:grid-cols-5">{[['Priority',stats.executivePriority],['Critical',stats.critical],['High',stats.high],['Investigation',stats.requiresInvestigation],['Decisions',stats.total]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-white/10 bg-white/[0.02] p-4"><div className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">{k}</div><div className="mt-1 text-2xl font-semibold text-white">{v}</div></div>)}</div>
  {error && <div className="rounded-lg border border-red-500/20 bg-red-500/5 p-3 text-xs text-red-300">{error}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.25fr_.95fr]">
   <section className="aegis-surface overflow-hidden rounded-2xl border border-white/10"><div className="border-b border-white/10 p-4"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Priority decision queue</div><div className="mt-1 text-xs text-slate-600">Select a decision to expose the reasoning and next action.</div></div>{data.decisions.map((d,i)=><button key={d.decisionId} onClick={()=>setSelected(d)} className={`w-full border-b border-white/5 p-4 text-left transition hover:bg-white/[0.03] ${selected?.decisionId===d.decisionId?'bg-cyan-400/[0.05]':''}`}><div className="flex items-center gap-3"><span className="text-xs text-slate-600">#{i+1}</span><div className="min-w-0 flex-1"><div className="font-medium text-slate-100">{d.label}</div><div className="mt-1 truncate text-xs text-slate-500">{d.recommendedAction}</div></div><div className="text-right"><div className="font-semibold text-white">{d.priority}</div><div className="text-[10px] text-slate-600">priority</div></div><ArrowRight size={16} className="text-slate-600"/></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-slate-500"><span>Risk {d.risk}</span><span>Confidence {d.confidence}%</span><span>Conflicts {d.conflicts}</span><span>Impact {d.executiveImpact}</span></div></button>)}</section>
   <aside className="aegis-surface rounded-2xl border border-white/10 p-5">{selected ? <div className="space-y-5"><div><div className="text-[10px] font-bold uppercase tracking-wider text-cyan-300">Selected decision</div><h2 className="mt-1 text-xl font-semibold text-white">{selected.label}</h2></div><DecisionIntelligencePanel risk={selected.risk} confidence={selected.confidence} conflicts={selected.conflicts} priority={selected.priority} executiveImpact={selected.executiveImpact} urgency={selected.urgency}/><div><div className="flex items-center gap-2 text-xs font-semibold text-slate-300"><AlertTriangle size={14}/> Investigation brief</div><p className="mt-2 text-sm leading-6 text-slate-400">{selected.investigationBrief}</p></div><div><div className="flex items-center gap-2 text-xs font-semibold text-slate-300"><ClipboardCheck size={14}/> Remediation brief</div><p className="mt-2 text-sm leading-6 text-slate-400">{selected.remediationBrief}</p></div><div><div className="text-xs font-semibold text-slate-300">Re-validation plan</div><ul className="mt-2 space-y-2 text-sm text-slate-400">{selected.revalidationPlan.map(x=><li key={x} className="flex gap-2"><CheckCircle2 size={15} className="mt-0.5 text-emerald-400"/>{x}</li>)}</ul></div><div className="grid grid-cols-3 gap-2"><Link to={`/validations/${selected.nodeId}/results`} className="rounded-lg border border-white/10 px-3 py-2 text-center text-xs font-semibold text-slate-300">Investigate</Link><Link to="/reports" className="rounded-lg border border-white/10 px-3 py-2 text-center text-xs font-semibold text-slate-300"><FileText size={14} className="mr-1 inline"/>Report</Link><button onClick={createAction} disabled={creating} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50"><Play size={14} className="mr-1 inline"/>{creating?'Creating…':'Start action'}</button></div></div> : <div className="grid min-h-[520px] place-items-center text-center"><div><ShieldAlert className="mx-auto h-8 w-8 text-slate-700"/><p className="mt-3 text-sm text-slate-500">Select a decision to inspect its intelligence and action path.</p></div></div>}</aside>
  </div>
 </div>
}
