import { useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Activity, AlertTriangle, Bell, CheckCircle2, ExternalLink, FileText, RefreshCw } from 'lucide-react'
import { Link } from 'react-router-dom'
import { apiHelpers } from '@/services/api'
import { cn } from '@/utils/cn'

type NotificationItem = {
  id: string
  event_type: string
  title: string
  message: string
  priority: 'low' | 'normal' | 'high' | 'urgent'
  status: string
  resource_type?: string
  resource_id?: string
  action_url?: string | null
  project_id?: string | null
  created_at: string
  read_at?: string | null
}

type NotificationsResponse = {
  items: NotificationItem[]
  count: number
  unread_count: number
}

const iconFor = (eventType: string, priority: NotificationItem['priority']) => {
  if (priority === 'urgent' || priority === 'high') return AlertTriangle
  if (eventType.startsWith('scan_') || eventType.startsWith('vuln_')) return Activity
  if (eventType.startsWith('report_')) return FileText
  return CheckCircle2
}

export const Notifications = () => {
  const query = useQuery<NotificationsResponse>({
    queryKey: ['notifications'],
    queryFn: () => apiHelpers.get<NotificationsResponse>('/notifications/'),
    refetchInterval: 15_000,
  })

  const items = useMemo(() => query.data?.items ?? [], [query.data])

  const markRead = async (id: string) => {
    await apiHelpers.post(`/notifications/${id}/read/`)
    await query.refetch()
  }

  const markAllRead = async () => {
    await apiHelpers.post('/notifications/read_all/')
    await query.refetch()
  }

  if (query.isLoading) return <div className="mx-auto grid min-h-[60vh] max-w-3xl place-items-center text-sm text-muted-foreground">Loading notifications from PostgreSQL…</div>

  if (query.isError) return (
    <div className="mx-auto grid min-h-[60vh] max-w-xl place-items-center p-6 text-center">
      <div>
        <Bell className="mx-auto h-8 w-8 text-destructive" />
        <h1 className="mt-3 text-lg font-semibold">Notifications unavailable</h1>
        <p className="mt-2 text-sm text-muted-foreground">The notification registry did not return a usable response. No placeholder notifications are shown.</p>
        <button type="button" onClick={() => query.refetch()} className="mt-4 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted"><RefreshCw className="h-3.5 w-3.5" /> Retry</button>
      </div>
    </div>
  )

  return (
    <div className="mx-auto max-w-3xl space-y-4">
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold"><Bell className="h-6 w-6 text-primary" /> Notifications</h1>
          <p className="mt-1 text-sm text-muted-foreground">Only notifications generated by real AegisScan events are displayed.</p>
        </div>
        {!!query.data?.unread_count && <button type="button" onClick={markAllRead} className="rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted">Mark all as read ({query.data.unread_count})</button>}
      </header>

      <section className="overflow-hidden rounded-xl border bg-card">
        {!items.length ? (
          <div className="p-12 text-center">
            <Bell className="mx-auto h-8 w-8 text-muted-foreground" />
            <p className="mt-3 font-medium">No notifications recorded</p>
            <p className="mt-1 text-sm text-muted-foreground">Notifications appear here only after a real scan, finding, report or system event is recorded.</p>
          </div>
        ) : (
          items.map((item) => {
            const Icon = iconFor(item.event_type, item.priority)
            const unread = item.status !== 'read'
            return (
              <div key={item.id} className={cn('flex gap-3 border-b px-4 py-4 last:border-0', unread && 'bg-primary/5')}>
                <Icon className={cn('mt-0.5 h-5 w-5', item.priority === 'urgent' ? 'text-destructive' : item.priority === 'high' ? 'text-amber-600' : 'text-primary')} />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-sm font-medium">{item.title}</span>
                    <span className="rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wide text-muted-foreground">{item.priority}</span>
                    {unread && <span className="rounded-full bg-primary px-2 py-0.5 text-[10px] font-semibold text-primary-foreground">New</span>}
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">{item.message}</p>
                  <div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] text-muted-foreground">
                    <span>{new Date(item.created_at).toLocaleString()}</span>
                    <span className="font-mono">{item.event_type}</span>
                    {item.resource_id && <span className="font-mono">{item.resource_type}:{item.resource_id}</span>}
                  </div>
                </div>
                <div className="flex shrink-0 items-center gap-1">
                  {item.action_url && <Link to={item.action_url} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Open related resource"><ExternalLink className="h-4 w-4" /></Link>}
                  {unread && <button type="button" onClick={() => markRead(item.id)} className="rounded-md border px-2 py-1 text-[11px] font-medium hover:bg-muted">Read</button>}
                </div>
              </div>
            )
          })
        )}
      </section>
    </div>
  )
}
