# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('rollout_percentage', models.PositiveIntegerField(default=0, verbose_name='rollout %')),
                ('target_users', models.JSONField(blank=True, default=list, verbose_name='target users')),
                ('target_groups', models.JSONField(blank=True, default=list, verbose_name='target groups')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='recurring')),
                ('recurrence_rule', models.CharField(blank=True, max_length=200, verbose_name='recurrence rule (RRULE)')),
                ('affected_services', models.JSONField(default=list, verbose_name='affected services')),
                ('notify_users', models.BooleanField(default=True, verbose_name='notify users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Window',
                'verbose_name_plural': 'Maintenance Windows',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('redis', 'Redis'), ('celery_worker', 'Celery Worker'), ('celery_beat', 'Celery Beat'), ('fastapi', 'FastAPI'), ('django', 'Django'), ('nginx', 'Nginx'), ('docker', 'Docker')], max_length=30, verbose_name='service')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=15, verbose_name='status')),
                ('host', models.CharField(default='localhost', max_length=100, verbose_name='host')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='port')),
                ('response_time_ms', models.FloatField(default=0, verbose_name='response time (ms)')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='details')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='last check')),
                ('last_status_change', models.DateTimeField(blank=True, null=True, verbose_name='last status change')),
                ('uptime_percentage', models.FloatField(default=100, verbose_name='uptime %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Status',
                'verbose_name_plural': 'Service Statuses',
                'ordering': ['service', 'host'],
                'unique_together': {('service', 'host', 'port')},
            },
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('cpu_usage', 'CPU Usage %'), ('memory_usage', 'Memory Usage %'), ('disk_usage', 'Disk Usage %'), ('network_in', 'Network In (bytes/s)'), ('network_out', 'Network Out (bytes/s)'), ('db_connections', 'DB Connections'), ('db_query_time', 'DB Query Time (ms)'), ('redis_memory', 'Redis Memory (MB)'), ('redis_connections', 'Redis Connections'), ('celery_workers', 'Celery Workers'), ('celery_queue_length', 'Celery Queue Length'), ('celery_active_tasks', 'Celery Active Tasks'), ('fastapi_requests', 'FastAPI Requests/min'), ('fastapi_latency', 'FastAPI Latency (ms)'), ('django_requests', 'Django Requests/min'), ('django_latency', 'Django Latency (ms)'), ('active_scans', 'Active Scans'), ('scan_duration_avg', 'Avg Scan Duration (s)'), ('findings_per_min', 'Findings per Minute')], max_length=50, verbose_name='metric type')),
                ('value', models.FloatField(verbose_name='value')),
                ('unit', models.CharField(max_length=20, verbose_name='unit')),
                ('labels', models.JSONField(blank=True, default=dict, verbose_name='labels')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='system_syst_metric__eac138_idx'), models.Index(fields=['timestamp'], name='system_syst_timesta_7d5242_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('scanning', 'Scanning'), ('notifications', 'Notifications'), ('integrations', 'Integrations'), ('storage', 'Storage'), ('performance', 'Performance'), ('custom', 'Custom')], max_length=20, verbose_name='category')),
                ('value', models.JSONField(verbose_name='value')),
                ('default_value', models.JSONField(verbose_name='default value')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('list', 'List'), ('password', 'Password')], max_length=20, verbose_name='value type')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='sensitive')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='readonly')),
                ('requires_restart', models.BooleanField(default=False, verbose_name='requires restart')),
                ('validation_rules', models.JSONField(blank=True, default=dict, verbose_name='validation rules')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('database', 'Database Only'), ('media', 'Media Files Only'), ('config', 'Configuration Only')], max_length=20, verbose_name='type')),
                ('storage', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3'), ('azure_blob', 'Azure Blob'), ('gcs', 'Google Cloud Storage'), ('ftp', 'FTP/SFTP')], max_length=20, verbose_name='storage')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15, verbose_name='status')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='file path')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='file hash (SHA256)')),
                ('encryption_enabled', models.BooleanField(default=True, verbose_name='encrypted')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration', models.FloatField(default=0, verbose_name='duration (seconds)')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='celery task ID')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='retention (days)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='system_back_status_2c7327_idx')],
            },
        ),
    ]
