# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel'), ('pdf', 'PDF')], max_length=10, verbose_name='format')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=15, verbose_name='status')),
                ('resource_type', models.CharField(max_length=50, verbose_name='resource type')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('fields', models.JSONField(blank=True, default=list, verbose_name='fields')),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='file')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='record count')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='downloaded at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export',
                'verbose_name_plural': 'Data Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('2fa_enable', '2FA Enabled'), ('2fa_disable', '2FA Disabled'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_role_change', 'User Role Changed'), ('user_permission_change', 'User Permission Changed'), ('project_create', 'Project Created'), ('project_update', 'Project Updated'), ('project_delete', 'Project Deleted'), ('project_archive', 'Project Archived'), ('project_clone', 'Project Cloned'), ('project_member_add', 'Project Member Added'), ('project_member_remove', 'Project Member Removed'), ('project_member_role_change', 'Project Member Role Changed'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Updated'), ('asset_delete', 'Asset Deleted'), ('scan_start', 'Scan Started'), ('scan_complete', 'Scan Completed'), ('scan_cancel', 'Scan Cancelled'), ('scan_restart', 'Scan Restarted'), ('scan_schedule', 'Scan Scheduled'), ('vuln_create', 'Vulnerability Created'), ('vuln_update', 'Vulnerability Updated'), ('vuln_status_change', 'Vulnerability Status Changed'), ('vuln_assign', 'Vulnerability Assigned'), ('vuln_note_add', 'Note Added to Vulnerability'), ('vuln_fix_verify', 'Vulnerability Fix Verified'), ('report_generate', 'Report Generated'), ('report_download', 'Report Downloaded'), ('report_share', 'Report Shared'), ('report_delete', 'Report Deleted'), ('compliance_assess', 'Compliance Assessed'), ('compliance_report', 'Compliance Report Generated'), ('knowledge_create', 'Knowledge Article Created'), ('knowledge_update', 'Knowledge Article Updated'), ('knowledge_publish', 'Knowledge Article Published'), ('settings_change', 'Settings Changed'), ('backup_create', 'Backup Created'), ('backup_restore', 'Backup Restored'), ('api_key_create', 'API Key Created'), ('api_key_revoke', 'API Key Revoked')], max_length=50, verbose_name='action')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial')], default='success', max_length=15, verbose_name='result')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='resource type')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='resource ID')),
                ('resource_repr', models.CharField(blank=True, max_length=200, verbose_name='resource representation')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='session ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, verbose_name='request ID')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('impersonated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['ip_address', 'created_at'], name='audit_audit_ip_addr_a8150a_idx'), models.Index(fields=['request_id'], name='audit_audit_request_06fe30_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute Force Attack'), ('suspicious_login', 'Suspicious Login'), ('privilege_escalation', 'Privilege Escalation'), ('data_exfiltration', 'Data Exfiltration'), ('unauthorized_access', 'Unauthorized Access'), ('config_change', 'Configuration Change'), ('scan_anomaly', 'Scan Anomaly'), ('vuln_spike', 'Vulnerability Spike')], max_length=30, verbose_name='event type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=15, verbose_name='severity')),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20, verbose_name='status')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='source IP')),
                ('target_resource_type', models.CharField(blank=True, max_length=50, verbose_name='target resource type')),
                ('target_resource_id', models.CharField(blank=True, max_length=100, verbose_name='target resource ID')),
                ('indicators', models.JSONField(default=list, verbose_name='indicators')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='raw data')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_events', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'severity'], name='audit_secur_event_t_3298e7_idx'), models.Index(fields=['status', 'created_at'], name='audit_secur_status_d4fdef_idx'), models.Index(fields=['target_user'], name='audit_secur_target__f84d3b_idx')],
            },
        ),
    ]
