# Generated by Django 5.2.17 on 2026-09-05 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_merge_0002'),
        ('enterprise', '0004_continuous_assurance_authorization_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportScheduleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_execution', to='audit.dataexport')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='enterprise.reportschedule')),
            ],
            options={
                'indexes': [models.Index(fields=['schedule', 'status'], name='enterprise__schedul_5d218a_idx'), models.Index(fields=['created_at'], name='enterprise__created_2ee443_idx')],
            },
        ),
    ]
