# Generated by Django 5.2.17 on 2026-09-05 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_reportscheduleexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipientDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.EmailField(max_length=254)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('artifact_sha256', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_deliveries', to='enterprise.reportscheduleexecution')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='enterprise__status_f51579_idx'), models.Index(fields=['recipient', 'created_at'], name='enterprise__recipie_d54890_idx')],
                'constraints': [models.UniqueConstraint(fields=('execution', 'recipient'), name='unique_report_execution_recipient')],
            },
        ),
    ]
