import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('enterprise', '0011_notification_source_security_event_and_more'),
        ('projects', '0002_initial'),
        ('vulnerabilities', '0002_delete_vulnerabilityevidence'),
        ('evidence', '0005_validationrun_authorization_decision'),
        ('scans', '0003_scan_authorization_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveWeightProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('weights', models.JSONField(default=dict)),
                ('learned_from', models.PositiveIntegerField(default=0)),
                ('reward_mean', models.FloatField(default=0)),
                ('algorithm', models.CharField(default='bounded-contextual-feedback-v1', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_weight_profiles', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_weight_profiles', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactIntegrityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=300)),
                ('source_ref', models.CharField(max_length=700)),
                ('sha256', models.CharField(max_length=64)),
                ('signature_verified', models.BooleanField(default=False)),
                ('provenance_verified', models.BooleanField(default=False)),
                ('package_namespace', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(choices=[('trusted','Trusted'),('review','Review'),('quarantined','Quarantined')], default='review', max_length=20)),
                ('quarantine_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_integrity_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_integrity_records', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_integrity_records', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BlastRadiusSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_ref', models.CharField(max_length=255)),
                ('crown_jewel_refs', models.JSONField(default=list)),
                ('impacted_nodes', models.JSONField(default=list)),
                ('score', models.FloatField(default=0)),
                ('evidence_refs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attack_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blast_radius_snapshots', to='enterprise.attackpath')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_radius_snapshots', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_radius_snapshots', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('asset','Asset'),('finding','Finding'),('evidence','Evidence'),('scan','Scan'),('validation','Validation'),('remediation','Remediation'),('user','User'),('audit','Audit'),('control','Control'),('threat','Threat')], max_length=20)),
                ('external_ref', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=300)),
                ('confidence', models.FloatField(default=1.0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_graph_nodes', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_graph_nodes', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='FindingDecisionProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=80)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('policy_ref', models.CharField(max_length=240)),
                ('reason', models.TextField()),
                ('evidence_refs', models.JSONField(default=list)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_decisions', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_decisions', to='projects.project')),
                ('validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finding_decisions', to='evidence.validationrun')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_provenance', to='vulnerabilities.vulnerability')),
            ],
            options={'ordering':['created_at','id']},
        ),
        migrations.CreateModel(
            name='FormalPolicyProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(max_length=80)),
                ('input_sha256', models.CharField(max_length=64)),
                ('satisfiable', models.BooleanField()),
                ('model', models.JSONField(blank=True, default=dict)),
                ('solver', models.CharField(default='z3', max_length=80)),
                ('solver_version', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_policy_proofs', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_policy_proofs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open','Open'),('investigating','Investigating'),('decided','Decided'),('closed','Closed')], default='open', max_length=20)),
                ('decision_summary', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ManyToManyField(blank=True, related_name='investigation_cases', to='evidence.evidence')),
                ('findings', models.ManyToManyField(blank=True, related_name='investigation_cases', to='vulnerabilities.vulnerability')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_cases', to='enterprise.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_investigation_cases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_cases', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScanControlCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=20)),
                ('phase', models.CharField(blank=True, max_length=80)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('progress', models.FloatField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('resume_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_checkpoints', to='scans.scan')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='enterprise.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='enterprise.team')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceGraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(max_length=60)),
                ('weight', models.FloatField(default=1.0)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_graph_edges', to='enterprise.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_graph_edges', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='enterprise.evidencegraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='enterprise.evidencegraphnode')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationCaseEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_case_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='enterprise.investigationcase')),
            ],
            options={'ordering':['id']},
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead','Lead'),('member','Member'),('viewer','Viewer')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='enterprise.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(model_name='adaptiveweightprofile',constraint=models.UniqueConstraint(fields=('project','version'),name='uniq_project_weight_version')),
        migrations.AddConstraint(model_name='artifactintegrityrecord',constraint=models.UniqueConstraint(fields=('project','sha256'),name='uniq_project_artifact_sha')),
        migrations.AddIndex(model_name='artifactintegrityrecord',index=models.Index(fields=['project','state'],name='idx_artifact_project_state')),
        migrations.AddIndex(model_name='blastradiussnapshot',index=models.Index(fields=['project','created_at'],name='idx_blast_project_created')),
        migrations.AddConstraint(model_name='evidencegraphnode',constraint=models.UniqueConstraint(fields=('project','kind','external_ref'),name='uniq_egraph_project_kind_ref')),
        migrations.AddIndex(model_name='evidencegraphnode',index=models.Index(fields=['project','kind'],name='idx_egraph_project_kind')),
        migrations.AddConstraint(model_name='evidencegraphedge',constraint=models.UniqueConstraint(fields=('project','source','target','edge_type'),name='uniq_egraph_edge')),
        migrations.AddIndex(model_name='evidencegraphedge',index=models.Index(fields=['project','edge_type'],name='idx_egraph_project_edge')),
        migrations.AddIndex(model_name='findingdecisionprovenance',index=models.Index(fields=['vulnerability','created_at'],name='idx_find_decision_created')),
        migrations.AddIndex(model_name='findingdecisionprovenance',index=models.Index(fields=['project','decision'],name='idx_find_decision_project')),
        migrations.AddIndex(model_name='formalpolicyproof',index=models.Index(fields=['project','proof_type','created_at'],name='idx_formal_proof_project')),
        migrations.AddIndex(model_name='investigationcase',index=models.Index(fields=['project','status'],name='idx_case_project_status')),
        migrations.AddIndex(model_name='investigationcase',index=models.Index(fields=['owner','status'],name='idx_case_owner_status')),
        migrations.AddConstraint(model_name='scancontrolcheckpoint',constraint=models.UniqueConstraint(fields=('scan','sequence'),name='uniq_scan_checkpoint_sequence')),
        migrations.AddIndex(model_name='scancontrolcheckpoint',index=models.Index(fields=['scan','created_at'],name='idx_scan_checkpoint_created')),
        migrations.AddConstraint(model_name='team',constraint=models.UniqueConstraint(fields=('organization','slug'),name='uniq_team_org_slug')),
        migrations.AddIndex(model_name='team',index=models.Index(fields=['organization','is_active'],name='idx_team_org_active')),
        migrations.AddConstraint(model_name='teammembership',constraint=models.UniqueConstraint(fields=('team','user'),name='uniq_team_user')),
        migrations.AddIndex(model_name='teammembership',index=models.Index(fields=['user','role'],name='idx_team_user_role')),
    ]
