import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('enterprise', '0015_decision_action_risk_correlation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationPolicyManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('tenant_ref', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.CharField(max_length=700)),
                ('method', models.CharField(max_length=16)),
                ('operation', models.CharField(blank=True, max_length=160)),
                ('resource_type', models.CharField(blank=True, max_length=160)),
                ('allowed', models.BooleanField()),
                ('ownership_rule', models.CharField(blank=True, max_length=160)),
                ('tenant_rule', models.CharField(blank=True, max_length=160)),
                ('sensitive_operation', models.BooleanField(default=False)),
                ('required_scopes', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('policy_source', models.CharField(choices=[
                    ('operator_declared', 'Operator Declared'),
                    ('source_annotation', 'Source Annotation'),
                    ('application_rbac', 'Application RBAC'),
                    ('oauth_scope', 'OAuth Scope'),
                    ('openapi_extension', 'OpenAPI Extension'),
                    ('observed_baseline', 'Observed Baseline'),
                ], max_length=40)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('canonical_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorization_policy_manifests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorization_policy_manifests', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['project', 'endpoint', 'method'], name='idx_authpol_endpoint'),
                    models.Index(fields=['project', 'role', 'tenant_ref'], name='idx_authpol_role_tenant'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ExecutionBudgetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('environment', models.CharField(choices=[
                    ('production', 'Production'),
                    ('staging', 'Staging'),
                    ('development', 'Development'),
                    ('digital_twin', 'Digital Twin'),
                ], max_length=20)),
                ('allowed_capabilities', models.JSONField(blank=True, default=list)),
                ('max_requests', models.PositiveIntegerField(default=1000)),
                ('network_io_bytes', models.BigIntegerField(default=104857600)),
                ('browser_sessions', models.PositiveIntegerField(default=2)),
                ('identities', models.PositiveIntegerField(default=5)),
                ('object_mutations', models.PositiveIntegerField(default=0)),
                ('parallelism', models.PositiveIntegerField(default=4)),
                ('cpu_seconds', models.PositiveIntegerField(default=300)),
                ('memory_mb', models.PositiveIntegerField(default=1024)),
                ('duration_seconds', models.PositiveIntegerField(default=900)),
                ('state_changes', models.BooleanField(default=False)),
                ('destructive_operations', models.BooleanField(default=False)),
                ('state_change_policy', models.CharField(default='deny', max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('canonical_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_budget_profiles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_budget_profiles', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'environment', '-created_at'], name='idx_budget_project_env')],
            },
        ),
        migrations.CreateModel(
            name='ProviderApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=180)),
                ('provider_version', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[
                    ('approved', 'Approved'),
                    ('experimental', 'Experimental'),
                    ('restricted', 'Restricted'),
                    ('rejected', 'Rejected'),
                ], max_length=20)),
                ('capability', models.CharField(max_length=180)),
                ('manifest', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('manifest_sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_approval_records', to='projects.project')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_approval_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'status'], name='idx_provider_project_state')],
                'constraints': [
                    models.UniqueConstraint(fields=('project', 'provider_name', 'provider_version', 'capability', 'status', 'manifest_sha256'), name='uniq_provider_approval_dec'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SecurityGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plane', models.CharField(choices=[
                    ('application', 'Application'),
                    ('identity', 'Identity'),
                    ('attack_surface', 'Attack Surface'),
                    ('adversary', 'Adversary'),
                    ('detection', 'Detection'),
                    ('risk', 'Risk'),
                    ('governance', 'Governance'),
                ], default='application', max_length=32)),
                ('kind', models.CharField(choices=[
                    ('page', 'Page'), ('endpoint', 'Endpoint'), ('channel', 'Channel'),
                    ('graphql_operation', 'GraphQL Operation'), ('websocket_channel', 'WebSocket Channel'),
                    ('identity', 'Identity'), ('session', 'Session'), ('role', 'Role'), ('tenant', 'Tenant'),
                    ('resource', 'Resource'), ('policy', 'Policy'), ('observation', 'Observation'),
                    ('evidence', 'Evidence'), ('finding', 'Finding'), ('attack_chain', 'Attack Chain'),
                    ('detection', 'Detection'), ('risk', 'Risk'), ('control', 'Control'),
                    ('remediation', 'Remediation'), ('revalidation', 'Revalidation'), ('service', 'Service'),
                    ('cache', 'Cache'), ('reverse_proxy', 'Reverse Proxy'), ('database', 'Database'),
                    ('external_service', 'External Service'), ('threat', 'Threat'), ('ttp', 'ATT&CK TTP'),
                    ('asset', 'Asset'), ('capability', 'Capability'), ('trust_boundary', 'Trust Boundary'),
                    ('data_flow', 'Data Flow'),
                ], max_length=40)),
                ('external_ref', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=300)),
                ('protocol', models.CharField(blank=True, max_length=32)),
                ('tenant_ref', models.CharField(blank=True, max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_graph_nodes', to='projects.project')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['project', 'plane', 'kind'], name='idx_secgraph_project_kind'),
                    models.Index(fields=['project', 'tenant_ref'], name='idx_secgraph_tenant'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('project', 'external_ref'), name='uniq_secgraph_project_ref'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SecurityGraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=80)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_graph_edges', to='projects.project')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_outgoing', to='enterprise.securitygraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incoming', to='enterprise.securitygraphnode')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'relation'], name='idx_secedge_project_rel')],
                'constraints': [
                    models.UniqueConstraint(fields=('project', 'source', 'target', 'relation'), name='uniq_secgraph_project_edge'),
                ],
            },
        ),
        migrations.CreateModel(
            name='WebSecurityValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[
                    ('authorization_matrix', 'Authorization Matrix'),
                    ('negative_path', 'Negative Path'),
                    ('response_comparison', 'Response Comparison'),
                ], max_length=40)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('contract_version', models.CharField(default='2.0', max_length=20)),
                ('input_sha256', models.CharField(max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_security_validation_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_security_validation_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'kind', '-created_at'], name='idx_webval_project_kind')],
            },
        ),
        migrations.CreateModel(
            name='WebSecurityObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_ref', models.CharField(max_length=255)),
                ('identity_ref', models.CharField(max_length=255)),
                ('identity_type', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('tenant_ref', models.CharField(blank=True, max_length=255)),
                ('resource_ref', models.CharField(blank=True, max_length=255)),
                ('resource_tenant_ref', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.CharField(max_length=700)),
                ('method', models.CharField(max_length=16)),
                ('operation', models.CharField(blank=True, max_length=160)),
                ('expected_allowed', models.BooleanField()),
                ('observed_decision', models.CharField(choices=[
                    ('allowed', 'Allowed'), ('denied', 'Denied'), ('error', 'Error'), ('indeterminate', 'Indeterminate'),
                ], max_length=20)),
                ('passed', models.BooleanField()),
                ('semantic', models.JSONField(default=dict)),
                ('evidence_fingerprint', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='enterprise.authorizationpolicymanifest')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='enterprise.websecurityvalidationrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [
                    models.Index(fields=['run', 'passed'], name='idx_webobs_run_pass'),
                    models.Index(fields=['identity_ref', 'resource_ref'], name='idx_webobs_identity_resource'),
                ],
            },
        ),
    ]
