# Generated by Django 5.2.17 on 2026-10-03 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0048_wstg_methodology_attestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurpMCPInvocationClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('invocation_sequence', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('in_flight', 'In flight'), ('committed', 'Committed'), ('indeterminate', 'Indeterminate')], default='in_flight', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim', to='enterprise.burpmcpinvocation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invocation_claims', to='enterprise.burpmcpsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'idempotency_key'), name='uniq_burp_claim_idem'), models.UniqueConstraint(fields=('session', 'invocation_sequence'), name='uniq_burp_claim_seq'), models.CheckConstraint(condition=models.Q(('state__in', ['in_flight', 'committed', 'indeterminate'])), name='burp_claim_known_state'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('invocation__isnull', False), ('state', 'committed')), models.Q(('invocation__isnull', True), ('state__in', ['in_flight', 'indeterminate'])), _connector='OR'), name='burp_claim_commit_binding')],
            },
        ),
    ]
