# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=15, verbose_name='severity')),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('accepted_risk', 'Accepted Risk'), ('wont_fix', "Won't Fix"), ('duplicate', 'Duplicate')], default='open', max_length=20, verbose_name='status')),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unverified', 'Unverified')], default='unverified', max_length=15, verbose_name='confidence')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='category')),
                ('cwe_id', models.CharField(blank=True, max_length=20, verbose_name='CWE ID')),
                ('cve_ids', models.JSONField(blank=True, default=list, verbose_name='CVE IDs')),
                ('owasp_category', models.CharField(blank=True, max_length=50, verbose_name='OWASP Category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='file path')),
                ('line_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='line start')),
                ('line_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='line end')),
                ('function_name', models.CharField(blank=True, max_length=200, verbose_name='function name')),
                ('code_snippet', models.TextField(blank=True, verbose_name='code snippet')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('parameter', models.CharField(blank=True, max_length=200, verbose_name='parameter')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='HTTP method')),
                ('cvss_score', models.FloatField(default=0, verbose_name='CVSS score')),
                ('cvss_vector', models.CharField(blank=True, max_length=100, verbose_name='CVSS vector')),
                ('risk_score', models.FloatField(default=0, verbose_name='risk score')),
                ('exploitability', models.FloatField(default=0, verbose_name='exploitability')),
                ('business_impact', models.FloatField(default=0, verbose_name='business impact')),
                ('evidence_count', models.PositiveIntegerField(default=0, verbose_name='evidence count')),
                ('verified_evidence_count', models.PositiveIntegerField(default=0, verbose_name='verified evidence count')),
                ('validation_status', models.CharField(blank=True, max_length=20, verbose_name='validation status')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validated at')),
                ('remediation', models.TextField(blank=True, verbose_name='remediation')),
                ('remediation_complexity', models.CharField(blank=True, choices=[('trivial', 'Trivial'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], max_length=20, verbose_name='remediation complexity')),
                ('remediation_effort', models.CharField(blank=True, max_length=50, verbose_name='remediation effort')),
                ('fix_available', models.BooleanField(default=False, verbose_name='fix available')),
                ('fix_version', models.CharField(blank=True, max_length=50, verbose_name='fix version')),
                ('references', models.JSONField(blank=True, default=list, verbose_name='references')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='assigned at')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('source_engine', models.CharField(blank=True, max_length=100, verbose_name='source engine')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='raw data')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='first seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='last seen')),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='fixed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vulnerabilities', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='vulnerabilities.vulnerability')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_vulnerabilities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='projects.project')),
                ('related_vulnerabilities', models.ManyToManyField(blank=True, related_name='related_to', to='vulnerabilities.vulnerability')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.scan')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_vulnerabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-severity', '-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='vulnerability_attachments/', verbose_name='file')),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('content_type', models.CharField(max_length=100, verbose_name='content type')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_attachments', to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vulnerabilities.vulnerability')),
            ],
            options={
                'verbose_name': 'Vulnerability Attachment',
                'verbose_name_plural': 'Vulnerability Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('static_analysis', 'Static Analysis'), ('dynamic_analysis', 'Dynamic Analysis'), ('log_analysis', 'Log Analysis'), ('config_check', 'Config Check'), ('dependency_scan', 'Dependency Scan'), ('external_intel', 'External Intelligence'), ('manual_review', 'Manual Review'), ('validation_test', 'Validation Test')], max_length=30, verbose_name='type')),
                ('quality', models.CharField(choices=[('verified', 'Verified'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unverified', 'Unverified')], default='unverified', max_length=15, verbose_name='quality')),
                ('source', models.CharField(max_length=100, verbose_name='source')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='location')),
                ('raw_data', models.TextField(blank=True, verbose_name='raw data')),
                ('confidence', models.FloatField(default=0.5, verbose_name='confidence')),
                ('corroboration_count', models.PositiveIntegerField(default=0, verbose_name='corroboration count')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidences', to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='vulnerabilities.vulnerability')),
            ],
            options={
                'verbose_name': 'Vulnerability Evidence',
                'verbose_name_plural': 'Vulnerability Evidences',
                'ordering': ['-quality', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='content')),
                ('is_private', models.BooleanField(default=False, verbose_name='private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_notes', to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='vulnerabilities.vulnerability')),
            ],
            options={
                'verbose_name': 'Vulnerability Note',
                'verbose_name_plural': 'Vulnerability Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('accepted_risk', 'Accepted Risk'), ('wont_fix', "Won't Fix"), ('duplicate', 'Duplicate')], max_length=20, verbose_name='old status')),
                ('new_status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('accepted_risk', 'Accepted Risk'), ('wont_fix', "Won't Fix"), ('duplicate', 'Duplicate')], max_length=20, verbose_name='new status')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_status_changes', to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='vulnerabilities.vulnerability')),
            ],
            options={
                'verbose_name': 'Vulnerability Status History',
                'verbose_name_plural': 'Vulnerability Status History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['project', 'severity', 'status'], name='vulnerabili_project_028b29_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['scan', 'severity'], name='vulnerabili_scan_id_cf8fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['asset', 'status'], name='vulnerabili_asset_i_8bf58b_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['assigned_to', 'status'], name='vulnerabili_assigne_0c95de_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['cve_ids'], name='vulnerabili_cve_ids_e19d87_idx'),
        ),
    ]
