# Generated by Django 5.2.17 on 2026-08-27 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('report_type', models.CharField(choices=[('technical', 'Technical Report'), ('executive', 'Executive Summary'), ('compliance', 'Compliance Report'), ('remediation', 'Remediation Report'), ('full', 'Full Validation Report'), ('comparison', 'Comparison Report'), ('trend', 'Trend Report')], default='full', max_length=20, verbose_name='type')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('markdown', 'Markdown'), ('json', 'JSON'), ('csv', 'CSV'), ('docx', 'DOCX')], default='pdf', max_length=15, verbose_name='format')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20, verbose_name='status')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='file')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size')),
                ('file_hash', models.CharField(blank=True, max_length=64, verbose_name='file hash')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, verbose_name='data snapshot')),
                ('generation_duration', models.FloatField(default=0, verbose_name='generation duration (seconds)')),
                ('template_used', models.CharField(blank=True, max_length=100, verbose_name='template used')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='share token')),
                ('share_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='share expires at')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='download count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='scans.scan')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('permission', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('comment', 'Comment')], default='view', max_length=20, verbose_name='permission')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='accessed at')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='access count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.report')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Share',
                'verbose_name_plural': 'Report Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('report_type', models.CharField(choices=[('technical', 'Technical Report'), ('executive', 'Executive Summary'), ('compliance', 'Compliance Report'), ('remediation', 'Remediation Report'), ('full', 'Full Validation Report'), ('comparison', 'Comparison Report'), ('trend', 'Trend Report')], max_length=20, verbose_name='type')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('markdown', 'Markdown'), ('json', 'JSON'), ('csv', 'CSV'), ('docx', 'DOCX')], max_length=15, verbose_name='format')),
                ('template_content', models.TextField(verbose_name='template content')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='variables')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('is_system', models.BooleanField(default=False, verbose_name='system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, verbose_name='frequency')),
                ('recipients', models.JSONField(default=list, verbose_name='recipients')),
                ('formats', models.JSONField(default=list, verbose_name='formats')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_generated', models.DateTimeField(blank=True, null=True, verbose_name='last generated')),
                ('next_generation', models.DateTimeField(verbose_name='next generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_generation'],
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('content', models.TextField(verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to='report_versions/', verbose_name='file')),
                ('changes', models.TextField(blank=True, verbose_name='changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_versions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Version',
                'verbose_name_plural': 'Report Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['project', 'report_type'], name='reports_rep_project_d2714d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['scan'], name='reports_rep_scan_id_357a64_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['share_token'], name='reports_rep_share_t_9bc35c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportversion',
            unique_together={('report', 'version_number')},
        ),
    ]
