# Generated by Django 5.2.8 on 2026-08-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='error message'),
        ),
    ]
