# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=20)),
                ('target_value', models.CharField(max_length=500)),
                ('scope', models.CharField(max_length=500)),
                ('profile', models.CharField(default='full', max_length=20)),
                ('engines', models.JSONField(default=list)),
                ('authorized', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('current_phase', models.CharField(default='queued', max_length=50)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('evidence_type', models.CharField(default='scanner_output', max_length=50)),
                ('raw_output', models.TextField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='assets.asset')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
