# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('scans', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_records', to='vulnerabilities.vulnerability'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['scan', 'source'], name='evidence_ev_scan_id_b4b4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['asset', 'collected_at'], name='evidence_ev_asset_i_8a688e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['finding', 'collected_at'], name='evidence_ev_finding_ee8e06_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['user', 'status'], name='evidence_va_user_id_7ca1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['target_value'], name='evidence_va_target__74e47b_idx'),
        ),
    ]
