# Generated by Django 5.2.17 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_initial'),
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='finding',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='validation_runs',
                to='vulnerabilities.vulnerability',
            ),
        ),
        migrations.AddIndex(
            model_name='validationrun',
            index=models.Index(fields=['finding', 'status'], name='evidence_va_finding_4a83d4_idx'),
        ),
    ]
