# Generated by Django 5.2.17 on 2026-09-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_validationrun_finding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='validationrun',
            new_name='evidence_va_finding_25b851_idx',
            old_name='evidence_va_finding_4a83d4_idx',
        ),
    ]
