# Generated by Django for governed finding dispositions.

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('evidence', '0006_findingconfirmation'),
        ('enterprise', '0021_cache_origin_security_validation_kind'),
        ('vulnerabilities', '0002_delete_vulnerabilityevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposition', models.CharField(choices=[('accepted_risk', 'Accepted Risk'), ('wont_fix', "Won't Fix"), ('duplicate', 'Duplicate')], max_length=20)),
                ('approving_role', models.CharField(max_length=20)),
                ('policy_version', models.CharField(default='finding-disposition.v1', max_length=64)),
                ('risk_correlation_sha256', models.CharField(blank=True, max_length=64)),
                ('request_fingerprint', models.CharField(max_length=64, unique=True)),
                ('rationale', models.TextField()),
                ('review_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_dispositions', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_disposition_records', to='vulnerabilities.vulnerability')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposition_records', to='vulnerabilities.vulnerability')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_dispositions', to='enterprise.organization')),
                ('risk_correlation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finding_dispositions', to='enterprise.riskcorrelationsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['finding', '-created_at'], name='idx_finddisp_finding_time'),
                    models.Index(fields=['organization', 'disposition'], name='idx_finddisp_org_kind'),
                    models.Index(fields=['review_at'], name='idx_finddisp_review_at'),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=(
                            models.Q(('disposition__in', ['accepted_risk', 'wont_fix']), ('risk_correlation__isnull', False), ('duplicate_of__isnull', True), ('review_at__isnull', False))
                            | models.Q(('disposition', 'duplicate'), ('risk_correlation__isnull', True), ('duplicate_of__isnull', False), ('review_at__isnull', True))
                        ),
                        name='evidence_disposition_lineage_shape',
                    )
                ],
            },
        ),
    ]
