import { useState, useRef, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/authStore'
import { useThemeStore } from '@/stores/themeStore'
import { useLanguageStore } from '@/stores/languageStore'
import { Breadcrumbs } from './Breadcrumbs'
import { Menu, Sun, Moon, Globe, Bell, User, LogOut, Settings, ChevronDown, Search, Command, Shield, Radio } from 'lucide-react'
import { cn } from '@/utils/cn'

export const Header = ({ sidebarOpen, onSidebarToggle, onMobileToggle, onCommandOpen }: { sidebarOpen: boolean; onSidebarToggle: () => void; onMobileToggle: () => void; onCommandOpen: () => void }) => {
  const { user, logout } = useAuthStore(); const { resolvedTheme, toggleTheme } = useThemeStore(); const { language, setLanguage } = useLanguageStore(); const navigate = useNavigate()
  const [notifOpen, setNotifOpen] = useState(false); const [userOpen, setUserOpen] = useState(false); const notifRef = useRef<HTMLDivElement>(null); const userRef = useRef<HTMLDivElement>(null)
  const displayName = user ? `${user.first_name} ${user.last_name}`.trim() || user.email : ''
  useEffect(() => { const h = (e: MouseEvent) => { if (notifRef.current && !notifRef.current.contains(e.target as Node)) setNotifOpen(false); if (userRef.current && !userRef.current.contains(e.target as Node)) setUserOpen(false) }; document.addEventListener('mousedown', h); return () => document.removeEventListener('mousedown', h) }, [])
  return <header className="sticky top-0 z-40 h-[68px] border-b border-border/70 bg-card/75 backdrop-blur-xl supports-[backdrop-filter]:bg-card/65">
    <div className="flex h-full items-center gap-3 px-4 lg:px-7">
      <button onClick={onMobileToggle} className="aegis-focus-visible rounded-xl p-2.5 hover:bg-accent lg:hidden"><Menu className="h-5 w-5" /></button>
      <button onClick={onSidebarToggle} className="aegis-focus-visible hidden rounded-xl p-2.5 hover:bg-accent lg:flex" aria-label="Toggle sidebar"><Menu className="h-5 w-5" /></button>
      <div className="hidden min-w-0 md:flex md:flex-col"><Breadcrumbs /><div className="hidden items-center gap-1.5 text-[10px] font-medium text-muted-foreground lg:flex"><span className="aegis-live-dot" /> Live assurance fabric · evidence-driven operations</div></div>
      <div className="flex flex-1 justify-center px-2"><button onClick={onCommandOpen} className="aegis-command aegis-focus-visible flex w-full max-w-xl items-center gap-3 rounded-xl px-3.5 py-2.5 text-sm text-muted-foreground transition hover:border-primary/30 hover:shadow-md"><Search className="h-4 w-4" /><span className="flex-1 text-start">Search validations, findings, assets...</span><span className="hidden items-center gap-1 rounded-md border bg-background/70 px-1.5 py-0.5 text-[10px] font-semibold md:inline-flex"><Command className="h-3 w-3" />K</span></button><button onClick={onCommandOpen} className="aegis-focus-visible rounded-xl border bg-muted p-2.5 sm:hidden"><Search className="h-4 w-4" /></button></div>
      <div className="flex items-center gap-1">
        <div className="hidden items-center gap-1 rounded-xl border bg-muted/40 px-2 py-1.5 xl:flex"><Radio className="h-3.5 w-3.5 text-emerald-500" /><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Live</span></div>
        <div className="relative" ref={notifRef}><button onClick={()=>setNotifOpen(!notifOpen)} className={cn('aegis-focus-visible relative rounded-xl p-2.5 hover:bg-accent', notifOpen && 'bg-accent')}><Bell className="h-5 w-5" /><span className="absolute right-1 top-1 h-4 min-w-4 rounded-full bg-destructive px-1 text-[10px] text-destructive-foreground grid place-items-center">3</span></button>{notifOpen && <div className="aegis-glass absolute right-0 top-full z-50 mt-2 w-80 overflow-hidden rounded-2xl shadow-2xl"><div className="flex items-center justify-between border-b px-4 py-3"><span className="text-sm font-bold">Notifications</span><Link to="/notifications" onClick={()=>setNotifOpen(false)} className="text-xs font-semibold text-primary hover:underline">View all</Link></div><div className="space-y-1 p-2">{[{title:'Validation completed',desc:'example.local — 9 findings',time:'2m ago'},{title:'Critical finding',desc:'IDOR on /api/users',time:'18m ago'},{title:'Report ready',desc:'Executive PDF generated',time:'1h ago'}].map((n,i)=><div key={i} className="rounded-xl px-3 py-2.5 hover:bg-muted"><div className="text-sm font-semibold">{n.title}</div><div className="text-xs text-muted-foreground">{n.desc} · {n.time}</div></div>)}</div></div>}</div>
        <button onClick={toggleTheme} className="aegis-focus-visible rounded-xl p-2.5 hover:bg-accent" aria-label="Toggle theme">{resolvedTheme==='dark' ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}</button>
        <button onClick={()=>setLanguage(language==='ar'?'en':'ar')} className="aegis-focus-visible hidden items-center gap-1 rounded-xl px-2.5 py-2 text-sm hover:bg-accent sm:flex"><Globe className="h-4 w-4" />{language==='ar'?'العربية':'EN'}</button>
        <div className="relative" ref={userRef}><button onClick={()=>setUserOpen(!userOpen)} className={cn('aegis-focus-visible flex items-center gap-2 rounded-full border px-1.5 py-1 hover:bg-accent', userOpen && 'bg-accent')}><div className="grid h-8 w-8 place-items-center rounded-full bg-primary text-sm font-bold text-primary-foreground">{user?.first_name?.[0]||'A'}{user?.last_name?.[0]||''}</div><span className="hidden max-w-[130px] truncate text-sm font-semibold md:block">{displayName}</span><ChevronDown className="h-4 w-4 text-muted-foreground" /></button>{userOpen && <div className="aegis-glass absolute right-0 top-full z-50 mt-2 w-64 overflow-hidden rounded-2xl shadow-2xl"><div className="border-b bg-muted/30 px-4 py-3"><div className="flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-full bg-primary text-primary-foreground"><User className="h-5 w-5" /></div><div><div className="text-sm font-bold">{displayName}</div><div className="flex items-center gap-1 text-xs capitalize text-muted-foreground"><Shield className="h-3 w-3" />{user?.role}</div></div></div><div className="mt-1 truncate font-mono text-xs text-muted-foreground">{user?.email}</div></div><div className="p-1.5"><button onClick={()=>{setUserOpen(false);navigate('/settings')}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-sm hover:bg-accent"><Settings className="h-4 w-4" />Settings</button><button onClick={async()=>{await logout();setUserOpen(false)}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-sm text-destructive hover:bg-destructive/10"><LogOut className="h-4 w-4" />Logout</button></div></div>}</div>
      </div>
    </div>
  </header>
}
