import { LayoutDashboard, FolderKanban, Server, Zap, Activity, Bug, FileText, ShieldCheck, BookOpen, GitBranch, TrendingUp, Users, Settings, Monitor, ClipboardList, Bell, Gauge, Database, Key, Siren, ListChecks, ListTodo, Search, FlaskConical } from 'lucide-react'

export const NAV_GROUPS = [
  { label: 'Overview', items: [{ name: 'Dashboard', href: '/dashboard', icon: LayoutDashboard, roles: ['all'] }] },
  { label: 'Workspace', items: [{ name: 'Projects', href: '/projects', icon: FolderKanban, roles: ['all'] }, { name: 'Assets', href: '/assets', icon: Server, roles: ['all'] }] },
  { label: 'Validate', items: [{ name: 'New Assessment', href: '/assess', icon: Zap, roles: ['security_analyst','security_manager','admin','super_admin'] }, { name: 'Validations', href: '/scan', icon: Activity, roles: ['all'] }, { name: 'Web Labs', href: '/web-labs', icon: FlaskConical, roles: ['security_analyst','security_manager','admin','super_admin'] }, { name: 'Findings', href: '/vulnerabilities', icon: Bug, roles: ['all'] }, { name: 'Evidence', href: '/evidence', icon: Database, roles: ['all'] }] },
  { label: 'Operate', items: [{ name: 'Operational Workspace', href: '/assurance/workflow', icon: ListTodo, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'Investigation Workspace', href: '/investigation', icon: Search, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'Decision Actions', href: '/assurance/actions', icon: ClipboardList, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'Enterprise Security', href: '/enterprise-security', icon: ShieldCheck, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }] },
  { label: 'Analyze', items: [{ name: 'Reports', href: '/reports', icon: FileText, roles: ['all'] }, { name: 'Compliance', href: '/compliance', icon: ShieldCheck, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'Security Assurance', href: '/assurance', icon: Gauge, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'WSTG Coverage', href: '/wstg', icon: ListChecks, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'Security Posture', href: '/posture', icon: TrendingUp, roles: ['security_manager','admin','super_admin'] }, { name: 'Digital Twin', href: '/digital-twin', icon: GitBranch, roles: ['security_analyst','security_manager','admin','super_admin'] }, { name: 'Knowledge', href: '/knowledge', icon: BookOpen, roles: ['all'] }] },
  { label: 'Manage', items: [{ name: 'Security Events', href: '/security-events', icon: Siren, roles: ['security_analyst','security_manager','admin','super_admin','auditor'] }, { name: 'Users & RBAC', href: '/users', icon: Users, roles: ['admin','super_admin'] }, { name: 'API Keys', href: '/keys', icon: Key, roles: ['security_manager','admin','super_admin'] }, { name: 'Audit Trail', href: '/audit', icon: ClipboardList, roles: ['admin','super_admin','auditor'] }, { name: 'Notifications', href: '/notifications', icon: Bell, roles: ['all'] }] },
  { label: 'System', items: [{ name: 'Settings', href: '/settings', icon: Settings, roles: ['admin','super_admin'] }, { name: 'System Monitor', href: '/system', icon: Monitor, roles: ['admin','super_admin'] }] },
]
