# Generated by Django 5.2

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='IntelligenceEnrichment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve_id', models.CharField(db_index=True, max_length=32)),
                ('sources', models.JSONField(default=dict)),
                ('source_urls', models.JSONField(default=dict)),
                ('provider_failures', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('snapshot_sha256', models.CharField(editable=False, max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_enrichments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['cve_id', '-observed_at'], name='intel_cve_observed_idx'),
                    models.Index(fields=['observed_by', '-observed_at'], name='intel_actor_observed_idx'),
                ],
            },
        ),
    ]
