import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuthStore } from '@/stores/authStore'

export const ForgotPassword = () => {
  const [params] = useSearchParams(); const token = params.get('reset') || ''
  const { forgotPassword, resetPassword } = useAuthStore(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [message,setMessage]=useState(''); const [done,setDone]=useState(false); const [busy,setBusy]=useState(false)
  const submit=async()=>{setBusy(true);setMessage('');try{if(token){await resetPassword(token,password);setMessage('تم تغيير كلمة المرور بنجاح.');}else{await forgotPassword(email);setMessage('إذا كان الحساب موجودًا، تم إرسال رابط الاستعادة.')}setDone(true)}catch(e:any){setMessage(e?.response?.data?.detail||e?.message||'تعذر تنفيذ العملية.')}finally{setBusy(false)}}
  return <div className="min-h-screen grid place-items-center bg-background p-6"><div className="w-full max-w-md rounded-3xl border bg-card p-7 shadow-xl"><h1 className="text-2xl font-black">{token?'تعيين كلمة مرور جديدة':'استعادة كلمة المرور'}</h1><p className="mt-2 text-sm text-muted-foreground">مسار استعادة آمن مرتبط بالـAPI.</p>{done?<div className="mt-6 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm">{message}<Link className="mt-3 block font-bold text-primary" to="/login">العودة لتسجيل الدخول</Link></div>:<div className="mt-6 space-y-4">{token?<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} placeholder="كلمة المرور الجديدة" className="w-full rounded-xl border bg-background px-4 py-3"/>:<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="user@company.com" className="w-full rounded-xl border bg-background px-4 py-3"/>}{message&&<div className="rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-xs text-destructive">{message}</div>}<button type="button" onClick={submit} disabled={busy||(!token&&!email)||(!!token&&password.length<8)} className="w-full rounded-xl bg-primary px-4 py-3 font-bold text-primary-foreground disabled:opacity-50">{busy?'جارٍ التنفيذ...':token?'تحديث كلمة المرور':'إرسال رابط الاستعادة'}</button></div>}</div></div>
}
