import { useMemo, useState } from 'react'
import { CheckCircle2, CircleHelp, FileSearch, Link2, ShieldAlert, Target } from 'lucide-react'

export type InvestigationEntity = { id: string; label: string; kind: 'finding' | 'asset' | 'service' | 'evidence' | 'data'; severity?: 'critical' | 'high' | 'medium' | 'low' | 'info'; status?: 'selected' | 'related' | 'impacted' | 'evidence-backed' | 'unknown' }

export function InvestigationInteractionModel({ entities, initialId, onChange }: { entities: InvestigationEntity[]; initialId?: string; onChange?: (entity: InvestigationEntity) => void }) {
  const [selectedId, setSelectedId] = useState(initialId ?? entities[0]?.id)
  const selected = entities.find((entity) => entity.id === selectedId)
  const related = useMemo(() => entities.filter((entity) => entity.id !== selectedId && entity.status !== 'unknown'), [entities, selectedId])
  const select = (entity: InvestigationEntity) => { setSelectedId(entity.id); onChange?.(entity) }

  if (!selected) return null
  return <section className="rounded-2xl border bg-card"><header className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><div className="flex items-center gap-2 font-semibold"><Target className="h-4 w-4 text-primary" /> Investigation context</div><p className="mt-1 text-xs text-muted-foreground">One selection drives every investigation layer.</p></div><div className="rounded-full border px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wide">{selected.kind}</div></header><div className="grid gap-5 p-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-xl border bg-muted/10 p-4"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border bg-background"><ShieldAlert className="h-5 w-5" /></div><div className="min-w-0"><div className="truncate text-sm font-bold">{selected.label}</div><div className="mt-1 flex flex-wrap gap-2 text-[10px] text-muted-foreground"><StateBadge icon={<CheckCircle2 className="h-3 w-3" />} label={selected.status ?? 'selected'} /><StateBadge icon={<FileSearch className="h-3 w-3" />} label={selected.severity ?? 'unclassified'} /></div></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Risk" value={selected.severity === 'critical' ? 'Critical' : selected.severity ?? '—'} /><Mini label="Context" value={related.length} /><Mini label="Evidence" value={entities.filter((e) => e.status === 'evidence-backed').length} /><Mini label="Unknown" value={entities.filter((e) => e.status === 'unknown').length} /></div></div><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Link2 className="h-3.5 w-3.5" /> Related entities</div><div className="space-y-1.5">{related.slice(0, 6).map((entity) => <button key={entity.id} type="button" onClick={() => select(entity)} className="flex w-full items-center justify-between rounded-lg border px-3 py-2 text-left hover:bg-muted"><span className="min-w-0 truncate text-xs font-medium">{entity.label}</span><span className="ml-3 flex shrink-0 items-center gap-1 text-[9px] text-muted-foreground"><StateBadge label={entity.status ?? 'related'} /> </span></button>)}</div></div></div></section>
}
function StateBadge({ icon, label }: { icon?: React.ReactNode; label: string }) { return <span className="inline-flex items-center gap-1 rounded-full border px-2 py-0.5">{icon}{label}</span> }
function Mini({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border bg-background px-3 py-2"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-0.5 text-xs font-bold">{value}</div></div> }
