import { useMemo, useState } from 'react'
import { Activity, CheckCircle2, Database, GitCompare, ShieldAlert, Signal, TriangleAlert } from 'lucide-react'
import type { AssuranceCorrelation, AssuranceSource } from './AssuranceDataSources'

const icons = { scanner: ShieldAlert, asset_inventory: Database, evidence: Signal, validation: GitCompare, compliance: CheckCircle2, threat_intel: TriangleAlert, ticketing: Activity }

export function MultiSourceAssurancePanel({ sources, correlations, onSelect }: { sources: AssuranceSource[]; correlations: AssuranceCorrelation[]; onSelect?: (correlation: AssuranceCorrelation) => void }) {
  const [selectedId, setSelectedId] = useState(correlations[0]?.entityId)
  const selected = correlations.find((item) => item.entityId === selectedId) ?? correlations[0]
  const healthy = sources.filter((source) => source.status === 'connected').length
  const avgTrust = sources.length ? Math.round(sources.reduce((sum, source) => sum + source.trust, 0) / sources.length) : 0
  const select = (item: AssuranceCorrelation) => { setSelectedId(item.entityId); onSelect?.(item) }

  return <section className="overflow-hidden rounded-2xl border bg-card"><header className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><div className="flex items-center gap-2 font-semibold"><Signal className="h-4 w-4 text-primary" /> Multi-source assurance</div><p className="mt-1 text-xs text-muted-foreground">Correlate independent signals before making a security decision.</p></div><div className="flex gap-2 text-[10px]"><span className="rounded-full border px-2 py-1">{healthy}/{sources.length} connected</span><span className="rounded-full border px-2 py-1">Trust {avgTrust}%</span></div></header><div className="grid lg:grid-cols-[minmax(0,1fr)_360px]"><div className="divide-y">{correlations.map((item) => { const active = item.entityId === selected?.entityId; return <button key={item.entityId} type="button" aria-pressed={active} onClick={() => select(item)} className={`flex w-full items-center gap-3 px-5 py-4 text-left transition hover:bg-muted/30 ${active ? 'bg-primary/5' : ''}`}><div className="grid h-9 w-9 place-items-center rounded-lg border bg-background"><Signal className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{item.entityId}</div><div className="mt-1 text-[10px] text-muted-foreground">{item.sourceCount} corroborating source(s) · {item.signals.length} signal(s)</div></div><div className="text-right"><div className="text-sm font-black">{item.confidence}%</div><div className="text-[9px] uppercase tracking-wider text-muted-foreground">confidence</div></div></button> })}{!correlations.length && <div className="p-8 text-center text-xs text-muted-foreground">No correlated assurance signals available.</div>}</div><aside className="border-t bg-muted/10 p-5 lg:border-l lg:border-t-0"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Correlation detail</div>{selected && <><h3 className="mt-2 text-sm font-bold">{selected.entityId}</h3><div className="mt-3 grid grid-cols-2 gap-2"><Mini label="Confidence" value={`${selected.confidence}%`} /><Mini label="Agreement" value={`${selected.agreement}%`} /><Mini label="Sources" value={selected.sourceCount} /><Mini label="Signals" value={selected.signals.length} /></div><div className="mt-4 space-y-2">{selected.signals.map((signal) => { const source = sources.find((item) => item.id === signal.sourceId); const Icon = source ? icons[source.kind] : Signal; return <div key={`${signal.sourceId}-${signal.signal}`} className="rounded-xl border bg-background p-3"><div className="flex items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-2 text-xs font-semibold"><Icon className="h-3.5 w-3.5" />{source?.name ?? signal.sourceId}</span><span className="text-[10px] font-bold">{signal.confidence}%</span></div><div className="mt-1 text-[10px] text-muted-foreground">{signal.signal} · value {Math.round(signal.value)}</div></div> })}</div></>}</aside></div></section>
}
function Mini({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border bg-background px-3 py-2"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div> }
