import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, CircleAlert, FileSearch, Gauge, ShieldAlert, ShieldCheck, Target } from 'lucide-react'

export type AssuranceCommandItem = { id: string; control: string; framework: string; status: 'pass' | 'fail' | 'partial' | 'not_assessed'; findings: number; evidence: number; validations: number; impact: number; risk: number; verified: boolean }

export function SecurityAssuranceCommandCenter({ items, onInvestigate, onOpenReport }: { items: AssuranceCommandItem[]; onInvestigate?: (item: AssuranceCommandItem) => void; onOpenReport?: (item: AssuranceCommandItem) => void }) {
  const [selectedId, setSelectedId] = useState(items[0]?.id ?? null)
  const selected = items.find((item) => item.id === selectedId)
  const summary = useMemo(() => ({ pass: items.filter((i) => i.status === 'pass').length, fail: items.filter((i) => i.status === 'fail').length, partial: items.filter((i) => i.status === 'partial').length, verified: items.filter((i) => i.verified).length }), [items])
  const exposure = useMemo(() => items.reduce((sum, item) => sum + Math.max(0, item.risk) * Math.max(1, item.findings), 0), [items])
  if (!items.length) return <section className="rounded-2xl border border-dashed bg-card p-10 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-3 text-sm font-semibold">Assurance command center is waiting for assessed controls</h2><p className="mt-1 text-xs text-muted-foreground">Run a validation with compliance mapping to establish the control → evidence chain.</p></section>
  return <section className="overflow-hidden rounded-2xl border bg-card">
    <header className="border-b px-5 py-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 font-semibold"><Gauge className="h-4 w-4 text-primary" /> Security Assurance Command Center</div><p className="mt-1 max-w-3xl text-xs text-muted-foreground">One decision surface connecting compliance controls, technical findings, evidence strength, validation proof, risk, and executive impact.</p></div><div className="rounded-xl border bg-background px-3 py-2 text-right"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">Exposure index</div><div className="text-lg font-black">{Math.round(exposure)}</div></div></div></header>
    <div className="grid grid-cols-2 gap-px border-b bg-border md:grid-cols-4"><Summary label="Passed" value={summary.pass} icon={<CheckCircle2 className="h-4 w-4" />} /><Summary label="Failed" value={summary.fail} icon={<CircleAlert className="h-4 w-4" />} /><Summary label="Partial" value={summary.partial} icon={<Target className="h-4 w-4" />} /><Summary label="Evidence-backed" value={summary.verified} icon={<FileSearch className="h-4 w-4" />} /></div>
    <div className="grid lg:grid-cols-[minmax(0,1fr)_380px]"><div className="divide-y">{items.map((item) => <button key={item.id} type="button" onClick={() => setSelectedId(item.id)} className={`flex w-full items-center gap-3 px-5 py-4 text-left transition hover:bg-muted/30 ${selectedId === item.id ? 'bg-primary/5' : ''}`} aria-pressed={selectedId === item.id}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border bg-background">{item.status === 'pass' ? <CheckCircle2 className="h-4 w-4 text-emerald-600" /> : item.status === 'fail' ? <ShieldAlert className="h-4 w-4 text-destructive" /> : <Target className="h-4 w-4 text-amber-600" />}</span><span className="min-w-0 flex-1"><span className="block text-[10px] uppercase tracking-wider text-muted-foreground">{item.framework}</span><span className="mt-0.5 block truncate text-xs font-semibold">{item.control}</span></span><span className="hidden text-right sm:block"><span className="block text-[10px] font-bold uppercase">Risk {item.risk}</span><span className="text-[9px] text-muted-foreground">{item.findings} findings · {item.evidence} evidence</span></span></button>)}</div>
      <aside className="border-t bg-muted/10 p-5 lg:border-l lg:border-t-0">{selected && <><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">Decision context</div><h3 className="mt-2 text-lg font-bold">{selected.control}</h3><div className="mt-1 text-xs text-muted-foreground">{selected.framework}</div><div className="mt-5 space-y-2"><Line icon={<ShieldAlert className="h-3.5 w-3.5" />} label="Risk" value={`${selected.risk}/100`} /><Line icon={<CircleAlert className="h-3.5 w-3.5" />} label="Findings" value={selected.findings} /><Line icon={<FileSearch className="h-3.5 w-3.5" />} label="Evidence" value={selected.evidence} /><Line icon={<ShieldCheck className="h-3.5 w-3.5" />} label="Validations" value={selected.validations} /><Line icon={<Target className="h-3.5 w-3.5" />} label="Executive impact" value={`${selected.impact}/100`} /></div><div className="mt-4 rounded-xl border bg-background p-3"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase"><CheckCircle2 className="h-3.5 w-3.5" /> Verification</div><p className="mt-1 text-[11px] text-muted-foreground">{selected.verified ? 'Current control result is backed by verified evidence.' : 'Current result still needs evidence-backed verification.'}</p></div><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={() => onInvestigate?.(selected)} className="inline-flex items-center justify-center gap-1 rounded-lg border px-3 py-2 text-xs font-semibold hover:bg-muted"><ArrowRight className="h-3 w-3" /> Investigate</button><button type="button" onClick={() => onOpenReport?.(selected)} className="rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">Executive report</button></div></>}</aside></div>
  </section>
}
function Summary({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="bg-card p-4"><div className="flex items-center gap-2 text-[10px] text-muted-foreground">{icon}{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div> }
function Line({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <div className="flex items-center justify-between rounded-lg border bg-background px-3 py-2"><span className="flex items-center gap-2 text-xs">{icon}{label}</span><span className="text-xs font-bold">{value}</span></div> }
