import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, CircleAlert, FileCheck2, Fingerprint, GitBranch, Network, ShieldCheck, Target, Zap } from 'lucide-react'

export type AssuranceGraphKind = 'asset' | 'control' | 'finding' | 'evidence' | 'validation' | 'attack-path' | 'risk' | 'decision' | 'action' | 'posture' | 'executive'
export type AssuranceGraphNode = { id: string; label: string; kind: AssuranceGraphKind; value?: string | number; confidence?: number; sources?: number; status?: 'positive' | 'warning' | 'critical' | 'neutral' }
export type AssuranceGraphLink = { from: string; to: string; relation: string; confidence?: number; conflict?: boolean }

const meta: Record<AssuranceGraphKind, { icon: any; label: string }> = {
  asset: { icon: Target, label: 'Asset' }, control: { icon: ShieldCheck, label: 'Control' }, finding: { icon: CircleAlert, label: 'Finding' }, evidence: { icon: Fingerprint, label: 'Evidence' }, validation: { icon: FileCheck2, label: 'Validation' }, 'attack-path': { icon: Network, label: 'Attack Path' }, risk: { icon: Target, label: 'Risk' }, decision: { icon: GitBranch, label: 'Decision' }, action: { icon: Zap, label: 'Action' }, posture: { icon: ShieldCheck, label: 'Posture' }, executive: { icon: CheckCircle2, label: 'Executive' },
}

export function UnifiedAssuranceGraph({ nodes, links }: { nodes: AssuranceGraphNode[]; links: AssuranceGraphLink[] }) {
  const [active, setActive] = useState<string | null>(null)
  const selected = nodes.find((node) => node.id === active)
  const layout = useMemo(() => {
    const order: AssuranceGraphKind[] = ['asset', 'control', 'finding', 'evidence', 'validation', 'attack-path', 'risk', 'decision', 'action', 'posture', 'executive']
    const result = new Map<string, { x: number; y: number }>()
    order.forEach((kind, column) => nodes.filter((node) => node.kind === kind).forEach((node, row) => result.set(node.id, { x: 75 + column * 150, y: 85 + row * 92 })))
    return result
  }, [nodes])
  if (!nodes.length) return <section className="rounded-2xl border bg-card p-8 text-center"><Network className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-3 text-sm font-semibold">Unified assurance graph awaiting live signals</p><p className="mt-1 text-xs text-muted-foreground">No provenance chain is available yet.</p></section>
  return <section className="overflow-hidden rounded-2xl border bg-card">
    <header className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-primary"><Network className="h-4 w-4" /> Unified Assurance Graph</div><h2 className="mt-1 text-lg font-semibold">Trace every executive signal to its security origin</h2><p className="mt-1 text-xs text-muted-foreground">Asset → control → finding → evidence → validation → attack path → risk → decision → action → posture → executive.</p></div><span className="rounded-lg border px-3 py-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{nodes.length} nodes · {links.length} relations</span></header>
    <div className="overflow-auto bg-[radial-gradient(circle_at_20%_20%,hsl(var(--primary)/.08),transparent_35%)] p-4"><svg viewBox="0 0 1680 430" className="min-w-[1500px]" role="img" aria-label="Unified assurance traceability graph"><defs><marker id="unified-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor" /></marker></defs>{links.map((link) => { const a=layout.get(link.from), b=layout.get(link.to); if(!a||!b)return null; return <g key={`${link.from}-${link.to}`} className={link.conflict ? 'text-red-400' : 'text-primary/35'}><path d={`M ${a.x+54} ${a.y} C ${a.x+90} ${a.y}, ${b.x-90} ${b.y}, ${b.x-54} ${b.y}`} fill="none" stroke="currentColor" strokeWidth={link.conflict?2.5:1.8} strokeDasharray={link.conflict?'3 3':'5 5'} markerEnd="url(#unified-arrow)" /><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-7} textAnchor="middle" className="fill-muted-foreground text-[9px]">{link.relation}{link.confidence !== undefined ? ` · ${link.confidence}%` : ''}{link.conflict ? ' · CONFLICT' : ''}</text></g> })}{nodes.map((node) => { const p=layout.get(node.id)!; const M=meta[node.kind]; const Icon=M.icon; return <g key={node.id} transform={`translate(${p.x-54},${p.y-30})`} onClick={()=>setActive(node.id)} className="cursor-pointer"><rect width="108" height="60" rx="10" className={active===node.id?'fill-primary/15 stroke-primary':'fill-card stroke-border'} strokeWidth={active===node.id?2:1.2}/><foreignObject width="108" height="60"><div className="flex h-full items-center gap-1.5 px-2"><Icon className="h-3.5 w-3.5 shrink-0 text-primary"/><div className="min-w-0"><div className="truncate text-[8px] font-bold uppercase tracking-wide text-muted-foreground">{M.label}</div><div className="truncate text-[10px] font-semibold">{node.label}</div>{node.value!==undefined&&<div className="truncate text-[9px] text-muted-foreground">{node.value}</div>}</div></div></foreignObject></g>})}</svg></div>
    {selected && <aside className="border-t bg-muted/10 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[9px] font-bold uppercase tracking-widest text-muted-foreground">Trace Inspector · {meta[selected.kind].label}</div><h3 className="mt-1 font-semibold">{selected.label}</h3></div><button type="button" onClick={()=>setActive(null)} className="rounded-lg border px-3 py-1.5 text-xs">Close</button></div><div className="mt-3 flex flex-wrap gap-2 text-[10px]">{selected.value!==undefined&&<span className="rounded-lg border bg-background px-3 py-2 font-semibold">Value: {selected.value}</span>}{selected.confidence!==undefined&&<span className="rounded-lg border bg-background px-3 py-2 font-semibold">Confidence: {selected.confidence}%</span>}{selected.sources!==undefined&&<span className="rounded-lg border bg-background px-3 py-2 font-semibold">Sources: {selected.sources}</span>}<span className="inline-flex items-center gap-1 rounded-lg border bg-background px-3 py-2 font-semibold"><ArrowRight className="h-3 w-3"/> Downstream trace</span></div></aside>}
  </section>
}
export default UnifiedAssuranceGraph
