import { Clock3, ShieldCheck, Siren, UserRound, Workflow } from 'lucide-react'

type Action = { actionId:string; title:string; owner:string; priority:number; state:string; sla?:{state:string; remainingHours:number; dueAt:string}; requiresApproval?:boolean }

const stateLabel: Record<string,string> = { pending:'Awaiting approval', approved:'Approved', assigned:'Assigned', in_progress:'In progress', awaiting_revalidation:'Re-validation', verified:'Verified', rejected:'Rejected', deferred:'Deferred' }

export function WorkflowControlTower({ actions, metrics, onOpen }: { actions:Action[]; metrics:{total:number;critical:number;onTrack:number;atRisk:number;breached:number;awaitingApproval:number;verified:number}; onOpen:(id:string)=>void }) {
 return <section className="space-y-4"><div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{[['Total',metrics.total],['Critical',metrics.critical],['On track',metrics.onTrack],['At risk',metrics.atRisk],['Breached',metrics.breached],['Approval',metrics.awaitingApproval],['Verified',metrics.verified]].map(([label,value])=><div key={String(label)} className="rounded-xl border bg-card p-3"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 text-xl font-black">{value}</div></div>)}</div><div className="overflow-hidden rounded-2xl border bg-card"><header className="flex items-center justify-between border-b px-5 py-4"><div><div className="flex items-center gap-2 font-semibold"><Workflow className="h-4 w-4 text-primary" /> Workflow Control Tower</div><p className="mt-1 text-xs text-muted-foreground">Operational view of remediation ownership, SLA pressure, approvals, and proof gates.</p></div><span className="rounded-full border px-2 py-1 text-[10px] font-semibold">{actions.length} active actions</span></header><div className="divide-y">{actions.map((action,index)=><button key={action.actionId} type="button" onClick={()=>onOpen(action.actionId)} className="flex w-full flex-wrap items-center gap-4 p-4 text-left transition hover:bg-muted/40"><span className="w-6 text-xs text-muted-foreground">#{index+1}</span><div className="min-w-[220px] flex-1"><div className="font-semibold text-sm">{action.title}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-[10px] text-muted-foreground"><span className="inline-flex items-center gap-1"><UserRound className="h-3 w-3" />{action.owner}</span><span className="rounded-full border px-2 py-0.5">{stateLabel[action.state] ?? action.state}</span></div></div><div className="text-right"><div className="text-xs font-bold">Priority {action.priority}</div><div className="mt-1 text-[10px] text-muted-foreground">{action.sla?.remainingHours !== undefined ? `${action.sla.remainingHours}h remaining` : 'SLA unavailable'}</div></div><div className="flex items-center gap-2 text-[10px] font-semibold">{action.requiresApproval && <span className="inline-flex items-center gap-1 rounded-full border px-2 py-1"><ShieldCheck className="h-3 w-3" /> Approval</span>}{action.sla?.state === 'breached' && <span className="inline-flex items-center gap-1 rounded-full border px-2 py-1 text-destructive"><Siren className="h-3 w-3" /> Breached</span>}{action.sla?.state === 'at_risk' && <span className="inline-flex items-center gap-1 rounded-full border px-2 py-1"><Clock3 className="h-3 w-3" /> At risk</span>}</div></button>)}{!actions.length && <div className="p-8 text-center text-sm text-muted-foreground">No remediation actions yet.</div>}</div></div></section>
}
