# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
        ('knowledge', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version', to='knowledge.knowledgearticle'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='knowledge.knowledgearticle'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='related_controls',
            field=models.ManyToManyField(blank=True, related_name='knowledge_articles', to='compliance.compliancecontrol'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='related_vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='knowledge_articles', to='vulnerabilities.vulnerability'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgearticlefeedback',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='knowledge.knowledgearticle'),
        ),
        migrations.AddField(
            model_name='knowledgearticlefeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgearticleview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='knowledge.knowledgearticle'),
        ),
        migrations.AddField(
            model_name='knowledgearticleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.knowledgecategory'),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.knowledgecategory'),
        ),
        migrations.AddField(
            model_name='remediationpattern',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remediationpattern',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgearticlefeedback',
            unique_together={('article', 'user')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['status', 'category'], name='knowledge_k_status_c571cb_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['tags'], name='knowledge_k_tags_751c39_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['author'], name='knowledge_k_author__2ea4bd_idx'),
        ),
    ]
