# Generated by Django 5.2

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
        ('scans', '0003_scan_authorization_decision'),
    ]
    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('security','Security'),('vulnerability','Vulnerability'),('compliance','Compliance'),('posture','Posture'),('executive','Executive')], max_length=30)),
                ('format', models.CharField(choices=[('json','JSON'),('html','HTML')], default='json', max_length=10)),
                ('status', models.CharField(choices=[('completed','Completed'),('failed','Failed')], default='completed', max_length=15)),
                ('snapshot', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='security-reports/')),
                ('snapshot_sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_security_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to='projects.project')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_reports', to='scans.scan')),
            ],
            options={'ordering': ['-created_at'], 'indexes': [models.Index(fields=['project', '-created_at'], name='reporting_project_created_idx')]},
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('security','Security'),('vulnerability','Vulnerability'),('compliance','Compliance'),('posture','Posture'),('executive','Executive')], max_length=30)),
                ('format', models.CharField(choices=[('json','JSON'),('html','HTML')], default='json', max_length=10)),
                ('frequency', models.CharField(choices=[('daily','Daily'),('weekly','Weekly'),('monthly','Monthly'),('cron','Cron')], max_length=15)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='projects.project')),
            ],
            options={'ordering': ['next_run', '-created_at'], 'indexes': [models.Index(fields=['project', 'is_active', 'next_run'], name='reporting_project_active_next_idx')]},
        ),
    ]
