global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: aegisscan-fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8001"]

  - job_name: aegisscan-celery
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8001"]
