# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(default=0, verbose_name='similarity score')),
                ('new_findings', models.JSONField(default=list, verbose_name='new findings')),
                ('fixed_findings', models.JSONField(default=list, verbose_name='fixed findings')),
                ('changed_findings', models.JSONField(default=list, verbose_name='changed findings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scan Comparison',
                'verbose_name_plural': 'Scan Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('display_name', models.CharField(max_length=150, verbose_name='display name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('recon', 'Reconnaissance'), ('analysis', 'Analysis'), ('intelligence', 'Threat Intelligence'), ('validation', 'Validation'), ('control', 'Control Validation'), ('coverage', 'Coverage Gap'), ('attack_path', 'Attack Path'), ('evidence_graph', 'Evidence Graph'), ('knowledge', 'Knowledge Management'), ('ai_explain', 'AI Explanation'), ('posture', 'Security Posture'), ('compliance', 'Compliance'), ('digital_twin', 'Digital Twin'), ('reporting', 'Reporting')], max_length=20, verbose_name='category')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='version')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deprecated', 'Deprecated'), ('experimental', 'Experimental')], default='active', max_length=20, verbose_name='status')),
                ('is_core', models.BooleanField(default=False, verbose_name='core engine')),
                ('requires_docker', models.BooleanField(default=False, verbose_name='requires docker')),
                ('timeout', models.PositiveIntegerField(default=300, verbose_name='timeout (seconds)')),
                ('config_schema', models.JSONField(blank=True, default=dict, verbose_name='config schema')),
                ('default_config', models.JSONField(blank=True, default=dict, verbose_name='default config')),
                ('dependencies', models.JSONField(blank=True, default=list, verbose_name='dependencies')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='execution order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scan Engine',
                'verbose_name_plural': 'Scan Engines',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScanEngineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='status')),
                ('progress', models.FloatField(default=0, verbose_name='progress %')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration', models.FloatField(default=0, verbose_name='duration (seconds)')),
                ('findings_found', models.PositiveIntegerField(default=0, verbose_name='findings found')),
                ('evidences_collected', models.PositiveIntegerField(default=0, verbose_name='evidences collected')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='result data')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('logs', models.TextField(blank=True, verbose_name='logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scan Engine Execution',
                'verbose_name_plural': 'Scan Engine Executions',
                'ordering': ['scan', 'engine__order'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10, verbose_name='level')),
                ('message', models.TextField(verbose_name='message')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('scan_type', models.CharField(choices=[('code', 'Code Scan'), ('url', 'URL Scan'), ('ip', 'IP Scan'), ('api', 'API Scan'), ('file', 'File Scan'), ('docker', 'Docker Image Scan'), ('network', 'Network Range Scan'), ('full_validation', 'Full Validation Platform')], max_length=30, verbose_name='scan type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partial', 'Partial')], default='pending', max_length=20, verbose_name='status')),
                ('depth', models.CharField(choices=[('quick', 'Quick (5 min)'), ('standard', 'Standard (15 min)'), ('deep', 'Deep (45 min)'), ('comprehensive', 'Comprehensive (2+ hours)')], default='standard', max_length=20, verbose_name='depth')),
                ('engines', models.JSONField(default=list, verbose_name='engines')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='configuration')),
                ('celery_task_id', models.CharField(blank=True, max_length=100, verbose_name='celery task ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('duration', models.FloatField(default=0, verbose_name='duration (seconds)')),
                ('progress', models.FloatField(default=0, verbose_name='progress %')),
                ('current_phase', models.CharField(blank=True, max_length=50, verbose_name='current phase')),
                ('current_engine', models.CharField(blank=True, max_length=100, verbose_name='current engine')),
                ('security_score', models.FloatField(default=0, verbose_name='security score')),
                ('risk_level', models.CharField(blank=True, max_length=20, verbose_name='risk level')),
                ('findings_count', models.PositiveIntegerField(default=0, verbose_name='findings count')),
                ('critical_count', models.PositiveIntegerField(default=0, verbose_name='critical count')),
                ('high_count', models.PositiveIntegerField(default=0, verbose_name='high count')),
                ('medium_count', models.PositiveIntegerField(default=0, verbose_name='medium count')),
                ('low_count', models.PositiveIntegerField(default=0, verbose_name='low count')),
                ('info_count', models.PositiveIntegerField(default=0, verbose_name='info count')),
                ('false_positive_count', models.PositiveIntegerField(default=0, verbose_name='false positive count')),
                ('engine_results', models.JSONField(blank=True, default=dict, verbose_name='engine results')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('error_traceback', models.TextField(blank=True, verbose_name='error traceback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
