# Generated by Django 5.2.17 on 2026-08-29 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project'),
        ),
        migrations.AddField(
            model_name='scan',
            name='scheduled_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_runs', to='projects.scheduledscan'),
        ),
        migrations.AddField(
            model_name='scan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='projects.scantemplate'),
        ),
        migrations.AddField(
            model_name='scancomparison',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scancomparison',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_comparisons', to='projects.project'),
        ),
        migrations.AddField(
            model_name='scancomparison',
            name='scan_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_a', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='scancomparison',
            name='scan_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_b', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='scanengineexecution',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scans.scanengine'),
        ),
        migrations.AddField(
            model_name='scanengineexecution',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_executions', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='engine_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='scans.scanengineexecution'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scans.scan'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['project', 'status'], name='scans_scan_project_c3c93a_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['project', 'scan_type'], name='scans_scan_project_095510_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['initiated_by'], name='scans_scan_initiat_152759_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['celery_task_id'], name='scans_scan_celery__7a4ced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scancomparison',
            unique_together={('scan_a', 'scan_b')},
        ),
        migrations.AlterUniqueTogether(
            name='scanengineexecution',
            unique_together={('scan', 'engine')},
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scan', 'level'], name='scans_scanl_scan_id_19c590_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scan', 'created_at'], name='scans_scanl_scan_id_372da0_idx'),
        ),
    ]
