import { CheckCircle2, CircleAlert, FileSearch, ShieldCheck, Target, TriangleAlert } from 'lucide-react'
import type { AssuranceCorrelation } from './AssuranceDataSources'

export function AssuranceDecisionMatrix({ correlation, onInvestigate, onGenerateReport }: { correlation?: AssuranceCorrelation; onInvestigate?: () => void; onGenerateReport?: () => void }) {
  if (!correlation) return <section className="rounded-2xl border border-dashed bg-card p-8 text-center text-sm text-muted-foreground">Select an entity to build an assurance decision.</section>
  const confidence = correlation.confidence
  const agreement = correlation.agreement
  const evidenceBacked = correlation.signals.filter((signal) => signal.signal === 'evidence').length > 0
  const decision = confidence >= 85 && agreement >= 80 ? 'Strong assurance' : confidence >= 65 && agreement >= 60 ? 'Review required' : 'Insufficient assurance'
  const decisionClass = confidence >= 85 && agreement >= 80 ? 'border-emerald-500/30 bg-emerald-500/5' : confidence >= 65 && agreement >= 60 ? 'border-amber-500/30 bg-amber-500/5' : 'border-red-500/30 bg-red-500/5'
  return <section className="overflow-hidden rounded-2xl border bg-card"><header className="border-b px-5 py-4"><div className="flex items-center gap-2 font-semibold"><Target className="h-4 w-4 text-primary" /> Assurance decision</div><p className="mt-1 text-xs text-muted-foreground">Separate corroboration quality from risk severity so decisions remain explainable.</p></header><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="grid gap-3 sm:grid-cols-3"><Score icon={<ShieldCheck className="h-4 w-4" />} label="Confidence" value={confidence} /><Score icon={<CheckCircle2 className="h-4 w-4" />} label="Agreement" value={agreement} /><Score icon={<FileSearch className="h-4 w-4" />} label="Evidence-backed" value={evidenceBacked ? 100 : 0} /></div><aside className={`rounded-2xl border p-5 ${decisionClass}`}><div className="flex items-center gap-2 text-xs font-semibold">{decision === 'Strong assurance' ? <CheckCircle2 className="h-4 w-4" /> : decision === 'Review required' ? <TriangleAlert className="h-4 w-4" /> : <CircleAlert className="h-4 w-4" />}{decision}</div><div className="mt-2 text-[11px] text-muted-foreground">{correlation.sourceCount} source(s) · {correlation.signals.length} signal(s)</div><div className="mt-5 flex gap-2"><button type="button" onClick={onInvestigate} className="flex-1 rounded-lg border bg-background px-3 py-2 text-[10px] font-semibold hover:bg-muted">Investigate</button><button type="button" onClick={onGenerateReport} className="flex-1 rounded-lg bg-primary px-3 py-2 text-[10px] font-semibold text-primary-foreground">Report</button></div></aside></div></section>
}
function Score({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="rounded-xl border bg-muted/10 p-4"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{icon}{label}</div><div className="mt-2 text-3xl font-black">{Math.round(value)}%</div><div className="mt-2 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all duration-500" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div></div> }
