import { useEffect, useMemo, useState } from 'react'
import { Crosshair, FileSearch, GitCompareArrows, ListFilter, Route, Search, ShieldAlert, ShieldCheck, Target, Wrench } from 'lucide-react'

export type InvestigationCommand = 'focus' | 'evidence' | 'conflicts' | 'attack' | 'blast' | 'compare' | 'control' | 'decision' | 'action' | 'revalidate'
type Props = { onCommand: (command: InvestigationCommand) => void; conflictCount?: number; disabled?: boolean }
const commands: Array<{ id: InvestigationCommand; label: string; icon: typeof Search; key: string }> = [
  { id: 'focus', label: 'Focus investigation', icon: Crosshair, key: 'F' }, { id: 'evidence', label: 'Trace evidence', icon: FileSearch, key: 'E' }, { id: 'conflicts', label: 'Show conflicts', icon: ListFilter, key: 'C' }, { id: 'attack', label: 'Attack path', icon: Route, key: 'A' }, { id: 'blast', label: 'Blast radius', icon: Target, key: 'B' }, { id: 'compare', label: 'Compare risk', icon: GitCompareArrows, key: 'R' }, { id: 'control', label: 'Open control', icon: ShieldCheck, key: 'O' }, { id: 'decision', label: 'Create decision', icon: ShieldAlert, key: 'D' }, { id: 'action', label: 'Remediate', icon: Wrench, key: 'M' }, { id: 'revalidate', label: 'Re-validate', icon: ShieldCheck, key: 'V' },
]
export function InvestigationCommandBar({ onCommand, conflictCount = 0, disabled = false }: Props) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState('')
  const filtered = useMemo(() => commands.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())), [query])
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(true) } if (event.key === 'Escape') setOpen(false) }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [])
  const run = (command: InvestigationCommand) => { setOpen(false); setQuery(''); onCommand(command) }
  return <section className="relative rounded-2xl border bg-card p-2 shadow-sm" aria-label="Investigation command bar">
    <button type="button" disabled={disabled} onClick={() => setOpen((value) => !value)} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm hover:bg-muted disabled:cursor-not-allowed disabled:opacity-60"><Search className="h-4 w-4 text-muted-foreground" /><span className="flex-1 text-muted-foreground">Search investigation, evidence, control, asset…</span><kbd className="rounded-md border bg-background px-2 py-1 text-[10px] text-muted-foreground">⌘ K</kbd></button>
    <div className="mt-1 flex flex-wrap gap-1.5 px-2 pb-1">{commands.slice(0, 6).map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => run(id)} className="inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-[11px] font-semibold text-muted-foreground hover:bg-muted hover:text-foreground"><Icon className="h-3.5 w-3.5" />{label}{id === 'conflicts' && conflictCount > 0 ? ` · ${conflictCount}` : ''}</button>)}</div>
    {open && <div className="absolute left-2 right-2 top-[calc(100%+8px)] z-40 overflow-hidden rounded-2xl border bg-popover shadow-2xl"><div className="border-b p-2"><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter commands…" className="w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring" /></div><div className="max-h-80 overflow-auto p-1">{filtered.map(({ id, label, icon: Icon, key }) => <button key={id} type="button" onClick={() => run(id)} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm hover:bg-muted"><Icon className="h-4 w-4 text-muted-foreground" /><span className="flex-1">{label}</span><kbd className="rounded border px-1.5 py-0.5 text-[10px] text-muted-foreground">{key}</kbd></button>)}{filtered.length === 0 && <p className="p-4 text-center text-xs text-muted-foreground">No investigation commands match.</p>}</div></div>}
  </section>
}
