import { CheckCircle2, CircleDashed, GitCompare, ShieldCheck, Sparkles } from 'lucide-react'

export type ProofEvent = { id: string; label: string; timestamp: string; type: 'detected' | 'remediation' | 'revalidation' | 'verified'; detail: string; evidenceCount?: number; risk?: number }

export function ProofOfFixTimeline({ events, beforeRisk, afterRisk, onVerify }: { events: ProofEvent[]; beforeRisk: number; afterRisk: number; onVerify?: () => void }) {
  const reduction = beforeRisk - afterRisk
  const verified = events.some((e) => e.type === 'verified')
  return <section className="overflow-hidden rounded-2xl border bg-card"><header className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-primary" /> Proof of Fix</div><p className="mt-1 text-xs text-muted-foreground">A chronological chain proving that remediation changed the observed security posture.</p></div>{!verified && <button type="button" onClick={onVerify} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground"><Sparkles className="h-3.5 w-3.5" /> Verify finding</button>}</header><div className="grid gap-5 p-5 lg:grid-cols-[1fr_320px]"><div className="relative space-y-3 pl-7">{events.map((event, index) => { const done = event.type !== 'verified' || verified; const Icon = event.type === 'verified' ? CheckCircle2 : event.type === 'revalidation' ? GitCompare : event.type === 'remediation' ? ShieldCheck : CircleDashed; return <div key={event.id} className="relative rounded-xl border bg-muted/10 p-3"><span className="absolute -left-[34px] top-3 grid h-7 w-7 place-items-center rounded-full border bg-card"><Icon className="h-3.5 w-3.5" /></span>{index < events.length - 1 && <span className="absolute -left-[21px] top-10 h-[calc(100%+12px)] w-px bg-border" />}<div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-xs font-bold">{event.label}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{event.detail}</div></div><span className="text-[9px] text-muted-foreground">{event.timestamp}</span></div>{(event.evidenceCount !== undefined || event.risk !== undefined) && <div className="mt-2 flex gap-2 text-[9px]">{event.evidenceCount !== undefined && <span className="rounded-full border px-2 py-0.5">{event.evidenceCount} evidence</span>}{event.risk !== undefined && <span className="rounded-full border px-2 py-0.5">Risk {event.risk}</span>}</div>}</div> })}</div><aside className="rounded-2xl border bg-muted/10 p-5"><div className="flex items-center gap-2 text-xs font-semibold"><GitCompare className="h-3.5 w-3.5" /> Evidence-backed delta</div><div className="mt-6 grid grid-cols-2 gap-3"><div><div className="text-[9px] uppercase tracking-wider text-muted-foreground">Before</div><div className="mt-1 text-3xl font-black">{beforeRisk}</div></div><div><div className="text-[9px] uppercase tracking-wider text-muted-foreground">After</div><div className="mt-1 text-3xl font-black">{afterRisk}</div></div></div><div className="mt-4 rounded-xl border bg-background p-3"><div className="text-[9px] uppercase tracking-wider text-muted-foreground">Risk reduction</div><div className="mt-1 text-2xl font-black">{reduction > 0 ? `−${reduction}` : `+${Math.abs(reduction)}`}</div><div className="mt-1 text-[10px] text-muted-foreground">{verified ? 'Verified by current evidence chain.' : 'Pending verification.'}</div></div></aside></div></section>
}
