# Generated by AegisScan credential vault implementation on 2026-09-09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('system', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('kind', models.CharField(choices=[('password', 'Password'), ('api_key', 'API Key'), ('token', 'Token'), ('ssh_private_key', 'SSH Private Key'), ('cloud_access_key', 'Cloud Access Key'), ('generic', 'Generic Secret')], default='generic', max_length=30, verbose_name='kind')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20, verbose_name='status')),
                ('scope', models.JSONField(blank=True, default=dict, verbose_name='scope')),
                ('encrypted_secret', models.TextField(verbose_name='encrypted secret')),
                ('secret_fingerprint', models.CharField(max_length=64, verbose_name='secret fingerprint')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='rotated at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_credential_secrets', to=settings.AUTH_USER_MODEL)),
                ('last_used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_credential_secrets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_secrets', to='projects.project')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_credential_secrets', to=settings.AUTH_USER_MODEL)),
                ('rotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_credential_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credential Secret',
                'verbose_name_plural': 'Credential Secrets',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CredentialAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('rotate', 'Rotate'), ('revoke', 'Revoke'), ('authorize_use', 'Authorize Use'), ('resolve_internal', 'Resolve Internal')], max_length=30, verbose_name='operation')),
                ('result', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failure', 'Failure')], max_length=20, verbose_name='result')),
                ('purpose', models.CharField(max_length=200, verbose_name='purpose')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('request_id', models.UUIDField(default=uuid.uuid4, verbose_name='request ID')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_access_events', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='system.credentialsecret')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_access_events', to='projects.project')),
            ],
            options={
                'verbose_name': 'Credential Access',
                'verbose_name_plural': 'Credential Access Events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='credentialsecret',
            index=models.Index(fields=['project', 'status', 'kind'], name='sys_cred_prj_status_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialsecret',
            index=models.Index(fields=['project', 'name'], name='sys_cred_prj_name_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialsecret',
            index=models.Index(fields=['secret_fingerprint'], name='sys_cred_fp_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialsecret',
            index=models.Index(fields=['last_used_at'], name='sys_cred_last_used_idx'),
        ),
        migrations.AddConstraint(
            model_name='credentialsecret',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='sys_cred_project_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='credentialaccess',
            index=models.Index(fields=['credential', '-created_at'], name='sys_ca_cred_created_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccess',
            index=models.Index(fields=['project', '-created_at'], name='sys_ca_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccess',
            index=models.Index(fields=['actor', '-created_at'], name='sys_ca_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccess',
            index=models.Index(fields=['operation', 'result', '-created_at'], name='sys_ca_op_result_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialaccess',
            index=models.Index(fields=['request_id'], name='sys_ca_request_idx'),
        ),
    ]
